export const GOUVERNEMENT_DATA = [
  {
    id: 'president',
    prenom: 'Emmanuel', nom: 'Macron',
    titre: 'Président de la République',
    titreShort: 'Président de la République',
    isPresident: true,
    photoUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Emmanuel_Macron_2025_(cropped).jpg?width=240',
    wikidataId: 'Q3052772',
    parti: 'RE',
    dateNomination: '2022-05-07',
    siteMinistere: 'https://www.elysee.fr/',
    servicePublicUrl: 'https://www.elysee.fr/en/contact/',
    twitter: 'EmmanuelMacron',
    sourceLabel: 'Élysée',
    sourceUrl: 'https://www.elysee.fr/emmanuel-macron',
    sourceUpdatedAt: '2026-03-25',
    openDataLinks: [
      {
        label: 'Open Data déplacements',
        url: 'https://www.data.gouv.fr/datasets/deplacements-des-presidents-de-la-republique-et-des-premiers-ministres-depuis-1945',
        source: 'data.gouv.fr',
      },
      {
        label: 'Open Data ministres',
        url: 'https://www.data.gouv.fr/datasets/liste-alphabetique-des-ministres-de-la-liberation-a-la-veme-republique',
        source: 'data.gouv.fr',
      },
    ],
    categories: ['energy','transport','social','security','health','finance','floods','fires','cyber','weather'],
    portefeuilles: ['présidence', 'élysée', 'chef de l\'état', 'diplomatie', 'défense', 'conseil des ministres'],
  },
  {
    id: 'pm',
    prenom: 'Sébastien', nom: 'Lecornu',
    titre: 'Premier Ministre',
    titreShort: 'Premier Ministre',
    isPM: true,
    wikidataId: 'Q20089181',
    parti: 'RE', nuanceCode: 'LREM',
    dateNomination: '2025-09-10',
    siteMinistere: 'https://www.info.gouv.fr',
    agendaUrl: 'https://www.info.gouv.fr/agenda/ministre/sebastien-lecornu',
    rssUrl: 'https://www.info.gouv.fr/flux-rss',
    twitter: 'SebLecornu',
    sourceLabel: 'Service-Public / JORF',
    sourceUrl: 'https://www.legifrance.gouv.fr/jorf/id/JORFTEXT000052380519',
    sourceUpdatedAt: '2026-03-19',
    appointmentUrl: 'https://www.legifrance.gouv.fr/jorf/id/JORFTEXT000052380519',
    appointmentLabel: 'Décret de nomination',
    openDataLinks: [
      {
        label: 'Open Data déplacements',
        url: 'https://www.data.gouv.fr/datasets/deplacements-des-presidents-de-la-republique-et-des-premiers-ministres-depuis-1945',
        source: 'data.gouv.fr',
      },
      {
        label: 'Open Data ministres',
        url: 'https://www.data.gouv.fr/datasets/liste-alphabetique-des-ministres-de-la-liberation-a-la-veme-republique',
        source: 'data.gouv.fr',
      },
    ],
    categories: ['energy','transport','social','security','health','finance','floods','fires','cyber','weather'],
    portefeuilles: ['premier ministre', 'gouvernement', 'matignon', 'conseil des ministres'],
  },
  {
    id: 'min-interieur',
    prenom: 'Laurent', nom: 'Nunez',
    titre: 'Ministre de l\'Intérieur',
    titreShort: 'Intérieur',
    wikidataId: 'Q30729111',
    dateNomination: '2025-10-12',
    siteMinistere: 'https://www.interieur.gouv.fr',
    agendaUrl: 'https://www.info.gouv.fr/agenda/ministre/laurent-nunez',
    rssUrl: 'https://www.interieur.gouv.fr/actualites/rss',
    sourceLabel: 'info.gouv.fr',
    sourceUrl: 'https://www.info.gouv.fr/personnalite/laurent-nunez',
    categories: ['security', 'fires'],
    portefeuilles: ['sécurité', 'police', 'gendarmerie', 'immigration', 'terrorisme', 'incendie'],
  },
  {
    id: 'min-economie',
    prenom: 'Roland', nom: 'Lescure',
    titre: 'Ministre de l\'Économie, des Finances et de la Souveraineté industrielle, énergétique et numérique',
    titreShort: 'Économie',
    wikidataId: 'Q30130489',
    dateNomination: '2025-10-12',
    siteMinistere: 'https://www.economie.gouv.fr',
    agendaUrl: 'https://www.info.gouv.fr/agenda/ministre/roland-lescure',
    rssUrl: 'https://www.economie.gouv.fr/rss/actualites',
    sourceLabel: 'info.gouv.fr',
    sourceUrl: 'https://www.info.gouv.fr/personnalite/roland-lescure',
    categories: ['finance', 'energy', 'cyber'],
    portefeuilles: ['économie', 'finances', 'bourse', 'cac40', 'budget', 'fiscalité', 'industrie', 'numérique', 'énergie'],
  },
  {
    id: 'min-affaires-etrangeres',
    prenom: 'Jean-Noël', nom: 'Barrot',
    titre: 'Ministre de l\'Europe et des Affaires étrangères',
    titreShort: 'Affaires étrangères',
    wikidataId: 'Q30339198',
    parti: 'MoDem', nuanceCode: 'LMDM',
    dateNomination: '2024-09-23',
    siteMinistere: 'https://www.diplomatie.gouv.fr',
    agendaUrl: 'https://www.info.gouv.fr/agenda/ministre/jean-noel-barrot',
    rssUrl: 'https://www.diplomatie.gouv.fr/fr/rss/actualites.xml',
    twitter: 'jnbarrot',
    sourceLabel: 'info.gouv.fr',
    sourceUrl: 'https://www.info.gouv.fr/personnalite/jean-noel-barrot',
    categories: ['security', 'cyber'],
    portefeuilles: ['diplomatie', 'europe', 'affaires étrangères', 'international'],
  },
  {
    id: 'min-ecologie',
    prenom: 'Monique', nom: 'Barbut',
    titre: 'Ministre de la Transition écologique, de la Biodiversité et des Négociations internationales sur le climat et la nature',
    titreShort: 'Énergie & Écologie',
    wikidataId: 'Q2403964',
    dateNomination: '2025-10-12',
    siteMinistere: 'https://www.ecologie.gouv.fr',
    agendaUrl: 'https://www.info.gouv.fr/agenda/ministre/monique-barbut',
    rssUrl: 'https://www.ecologie.gouv.fr/actualites/rss',
    sourceLabel: 'info.gouv.fr',
    sourceUrl: 'https://www.info.gouv.fr/personnalite/monique-barbut',
    categories: ['energy', 'weather', 'floods', 'fires'],
    portefeuilles: ['écologie', 'biodiversité', 'climat', 'nature', 'crues', 'inondations', 'feux', 'transition écologique'],
  },
  {
    id: 'min-travail',
    prenom: 'Jean-Pierre', nom: 'Farandou',
    titre: 'Ministre du Travail et des Solidarités',
    titreShort: 'Travail',
    wikidataId: 'Q33106208',
    dateNomination: '2025-10-12',
    siteMinistere: 'https://travail-emploi.gouv.fr',
    agendaUrl: 'https://www.info.gouv.fr/agenda/ministre/jean-pierre-farandou',
    rssUrl: 'https://travail-emploi.gouv.fr/actualites/rss',
    sourceLabel: 'info.gouv.fr',
    sourceUrl: 'https://www.info.gouv.fr/personnalite/jean-pierre-farandou',
    categories: ['social'],
    portefeuilles: ['travail', 'solidarités', 'emploi', 'grève', 'syndicat', 'chômage', 'retraite'],
  },
  {
    id: 'min-sante',
    prenom: 'Stéphanie', nom: 'Rist',
    titre: 'Ministre de la Santé, des Familles, de l\'Autonomie et des Personnes handicapées',
    titreShort: 'Santé',
    wikidataId: 'Q30339281',
    dateNomination: '2025-10-12',
    siteMinistere: 'https://sante.gouv.fr',
    agendaUrl: 'https://www.info.gouv.fr/agenda/ministre/stephanie-rist',
    rssUrl: 'https://sante.gouv.fr/actualites-presse/rss',
    sourceLabel: 'info.gouv.fr',
    sourceUrl: 'https://www.info.gouv.fr/personnalite/stephanie-rist',
    categories: ['health'],
    portefeuilles: ['santé', 'familles', 'autonomie', 'handicap', 'hôpital', 'épidémie', 'urgences', 'soins', 'médicament'],
  },
  {
    id: 'min-transports',
    prenom: 'Philippe', nom: 'Tabarot',
    titre: 'Ministre des Transports',
    titreShort: 'Transports',
    wikidataId: 'Q63371158',
    parti: 'LR', nuanceCode: 'LLR',
    dateNomination: '2025-01-13',
    siteMinistere: 'https://www.ecologie.gouv.fr',
    agendaUrl: 'https://www.info.gouv.fr/agenda/ministre/philippe-tabarot',
    rssUrl: 'https://www.ecologie.gouv.fr/actualites/rss',
    twitter: 'philippetabarot',
    sourceLabel: 'info.gouv.fr',
    sourceUrl: 'https://www.info.gouv.fr/personnalite/philippe-tabarot',
    categories: ['transport'],
    portefeuilles: ['transports', 'sncf', 'ratp', 'train', 'avion', 'autoroute', 'trafic', 'routier'],
  },
  {
    id: 'min-numerique',
    prenom: 'Anne', nom: 'Le Hénanff',
    titre: 'Ministre déléguée chargée de l\'Intelligence artificielle et du Numérique',
    titreShort: 'Numérique & IA',
    wikidataId: 'Q112651320',
    dateNomination: '2025-10-12',
    siteMinistere: 'https://www.economie.gouv.fr',
    agendaUrl: 'https://www.info.gouv.fr/agenda/ministre/anne-le-henanff',
    sourceLabel: 'info.gouv.fr',
    sourceUrl: 'https://www.info.gouv.fr/personnalite/anne-le-henanff',
    categories: ['cyber'],
    portefeuilles: ['cyber', 'numérique', 'internet', 'ia', 'données', 'cert-fr', 'anssi'],
  },
  {
    id: 'min-defense',
    prenom: 'Catherine', nom: 'Vautrin',
    titre: 'Ministre des Armées et des Anciens combattants',
    titreShort: 'Armées',
    wikidataId: 'Q2942097',
    dateNomination: '2025-10-12',
    siteMinistere: 'https://www.defense.gouv.fr',
    agendaUrl: 'https://www.info.gouv.fr/agenda/ministre/catherine-vautrin',
    rssUrl: 'https://www.defense.gouv.fr/actualites/rss',
    sourceLabel: 'info.gouv.fr',
    sourceUrl: 'https://www.info.gouv.fr/personnalite/catherine-vautrin',
    categories: ['security'],
    portefeuilles: ['défense', 'armée', 'militaire', 'marine', 'aviation', 'otan', 'renseignement'],
  },
];
