import type { HydraulicBackboneSeed } from './hydraulic-backbone.ts';

export const HYDRAULIC_OFFICIAL_BACKBONE_SEEDS = [
  {
    id: 'hyd-official-le-cheylas',
    name: "Le Cheylas",
    type: 'step_storage',
    subtype: 'pumped_storage',
    location: { lat: 45.380302, lon: 5.994444, region: "Auvergne-Rhône-Alpes", country: 'FR' },
    capacity_mw: 485,
    reservoir_volume: null,
    operator: null,
    river: null,
    commune: "Le Cheylas",
    department: "Isère",
    technology: "Pompage turbinage",
    head_m: 261,
    annual_generation_gwh: null,
    location_accuracy: "commune",
    official_name: "CHEYLAS",
    source_date: "2025-09-30",
    verification_sources: ['Registre national RTE/ODRE (30/09/2025)', 'Base Adresse Nationale'],
    selection_reason: "STEP >50 MW issue du registre national RTE/ODRE",
  },
  {
    id: 'hyd-official-villarodin',
    name: "Villarodin",
    type: 'hydro_production',
    subtype: 'dam',
    location: { lat: 45.215791, lon: 6.721873, region: "Auvergne-Rhône-Alpes", country: 'FR' },
    capacity_mw: 357,
    reservoir_volume: null,
    operator: null,
    river: null,
    commune: "Avrieux",
    department: "Savoie",
    technology: "Lac",
    head_m: 888.4,
    annual_generation_gwh: null,
    location_accuracy: "commune",
    official_name: "VILLARODIN",
    source_date: "2025-09-30",
    verification_sources: ['Registre national RTE/ODRE (30/09/2025)', 'Base Adresse Nationale'],
    selection_reason: "Grand aménagement hydraulique >50 MW issu du registre national RTE/ODRE",
  },
  {
    id: 'hyd-official-bollene',
    name: "Bollène",
    type: 'hydro_production',
    subtype: 'run_of_river',
    location: { lat: 44.286032, lon: 4.757798, region: "Provence-Alpes-Côte d'Azur", country: 'FR' },
    capacity_mw: 345,
    reservoir_volume: null,
    operator: null,
    river: null,
    commune: "Bollène",
    department: "Vaucluse",
    technology: "Fil de l'eau",
    head_m: 26.7,
    annual_generation_gwh: null,
    location_accuracy: "commune",
    official_name: "BOLLENE (SPECIALISE)",
    source_date: "2025-09-30",
    verification_sources: ['Registre national RTE/ODRE (30/09/2025)', 'Base Adresse Nationale'],
    selection_reason: "Usine au fil de l’eau structurante >50 MW issue du registre national RTE/ODRE",
  },
  {
    id: 'hyd-official-chateauneuf-du-rhone',
    name: "Châteauneuf-du-Rhône",
    type: 'hydro_production',
    subtype: 'run_of_river',
    location: { lat: 45.021295, lon: 4.934763, region: "Auvergne-Rhône-Alpes", country: 'FR' },
    capacity_mw: 285,
    reservoir_volume: null,
    operator: null,
    river: null,
    commune: "Châteauneuf-du-Rhône",
    department: "Drôme",
    technology: "Fil de l'eau",
    head_m: 19,
    annual_generation_gwh: null,
    location_accuracy: "commune",
    official_name: "CHATEAUNEUF-DU-RHONE",
    source_date: "2025-09-30",
    verification_sources: ['Registre national RTE/ODRE (30/09/2025)', 'Base Adresse Nationale'],
    selection_reason: "Usine au fil de l’eau structurante >50 MW issue du registre national RTE/ODRE",
  },
  {
    id: 'hyd-official-bort',
    name: "Bort",
    type: 'hydro_production',
    subtype: 'dam',
    location: { lat: 45.385671, lon: 2.495539, region: "Nouvelle-Aquitaine", country: 'FR' },
    capacity_mw: 232.2,
    reservoir_volume: null,
    operator: null,
    river: null,
    commune: "Bort-les-Orgues",
    department: "Corrèze",
    technology: "Lac",
    head_m: 114.8,
    annual_generation_gwh: null,
    location_accuracy: "commune",
    official_name: "BORT H-CENTRALE HYDRAULIQUE DE BORT",
    source_date: "2025-09-30",
    verification_sources: ['Registre national RTE/ODRE (30/09/2025)', 'Base Adresse Nationale'],
    selection_reason: "Grand aménagement hydraulique >50 MW issu du registre national RTE/ODRE",
  },
  {
    id: 'hyd-official-beauchastel',
    name: "Beauchastel",
    type: 'hydro_production',
    subtype: 'run_of_river',
    location: { lat: 44.827049, lon: 4.796512, region: "Auvergne-Rhône-Alpes", country: 'FR' },
    capacity_mw: 222,
    reservoir_volume: null,
    operator: null,
    river: null,
    commune: "Beauchastel",
    department: "Ardèche",
    technology: "Fil de l'eau",
    head_m: 13.4,
    annual_generation_gwh: null,
    location_accuracy: "commune",
    official_name: "BEAUCHASTEL",
    source_date: "2025-09-30",
    verification_sources: ['Registre national RTE/ODRE (30/09/2025)', 'Base Adresse Nationale'],
    selection_reason: "Usine au fil de l’eau structurante >50 MW issue du registre national RTE/ODRE",
  },
  {
    id: 'hyd-official-sisteron',
    name: "Sisteron",
    type: 'hydro_production',
    subtype: 'dam',
    location: { lat: 44.195961, lon: 5.941969, region: "Provence-Alpes-Côte d'Azur", country: 'FR' },
    capacity_mw: 214,
    reservoir_volume: null,
    operator: null,
    river: null,
    commune: "Sisteron",
    department: "Alpes-de-Haute-Provence",
    technology: "Lac",
    head_m: 116.4,
    annual_generation_gwh: null,
    location_accuracy: "commune",
    official_name: "SISTERON",
    source_date: "2025-09-30",
    verification_sources: ['Registre national RTE/ODRE (30/09/2025)', 'Base Adresse Nationale'],
    selection_reason: "Grand aménagement hydraulique >50 MW issu du registre national RTE/ODRE",
  },
  {
    id: 'hyd-official-beaucaire',
    name: "Beaucaire",
    type: 'hydro_production',
    subtype: 'run_of_river',
    location: { lat: 43.805922, lon: 4.643438, region: "Occitanie", country: 'FR' },
    capacity_mw: 210,
    reservoir_volume: null,
    operator: null,
    river: null,
    commune: "Beaucaire",
    department: "Gard",
    technology: "Fil de l'eau",
    head_m: 15,
    annual_generation_gwh: null,
    location_accuracy: "commune",
    official_name: "BEAUCAIRE",
    source_date: "2025-09-30",
    verification_sources: ['Registre national RTE/ODRE (30/09/2025)', 'Base Adresse Nationale'],
    selection_reason: "Usine au fil de l’eau structurante >50 MW issue du registre national RTE/ODRE",
  },
  {
    id: 'hyd-official-vallorcine',
    name: "Vallorcine",
    type: 'hydro_production',
    subtype: 'dam',
    location: { lat: 46.050277, lon: 6.942040, region: "Auvergne-Rhône-Alpes", country: 'FR' },
    capacity_mw: 190,
    reservoir_volume: null,
    operator: null,
    river: null,
    commune: "Vallorcine",
    department: "Haute-Savoie",
    technology: "Lac",
    head_m: 805,
    annual_generation_gwh: null,
    location_accuracy: "commune",
    official_name: "VALLORCINE",
    source_date: "2025-09-30",
    verification_sources: ['Registre national RTE/ODRE (30/09/2025)', 'Base Adresse Nationale'],
    selection_reason: "Grand aménagement hydraulique >50 MW issu du registre national RTE/ODRE",
  },
  {
    id: 'hyd-official-oraison',
    name: "Oraison",
    type: 'hydro_production',
    subtype: 'dam',
    location: { lat: 43.890169, lon: 5.908065, region: "Provence-Alpes-Côte d'Azur", country: 'FR' },
    capacity_mw: 187,
    reservoir_volume: null,
    operator: null,
    river: null,
    commune: "Oraison",
    department: "Alpes-de-Haute-Provence",
    technology: "Lac",
    head_m: 86.7,
    annual_generation_gwh: null,
    location_accuracy: "commune",
    official_name: "ORAISON",
    source_date: "2025-09-30",
    verification_sources: ['Registre national RTE/ODRE (30/09/2025)', 'Base Adresse Nationale'],
    selection_reason: "Grand aménagement hydraulique >50 MW issu du registre national RTE/ODRE",
  },
  {
    id: 'hyd-official-bourg-les-valence',
    name: "Bourg-lès-Valence",
    type: 'hydro_production',
    subtype: 'run_of_river',
    location: { lat: 44.939419, lon: 4.892455, region: "Auvergne-Rhône-Alpes", country: 'FR' },
    capacity_mw: 186,
    reservoir_volume: null,
    operator: null,
    river: null,
    commune: "Bourg-lès-Valence",
    department: "Drôme",
    technology: "Fil de l'eau",
    head_m: 12.37,
    annual_generation_gwh: null,
    location_accuracy: "site",
    official_name: "BOURG-LES-VALENCE",
    source_date: "2025-09-30",
    verification_sources: ['Registre national RTE/ODRE (30/09/2025)', 'Base Adresse Nationale'],
    selection_reason: "Usine au fil de l’eau structurante >50 MW issue du registre national RTE/ODRE",
  },
  {
    id: 'hyd-official-fessenheim',
    name: "Fessenheim",
    type: 'hydro_production',
    subtype: 'run_of_river',
    location: { lat: 47.913160, lon: 7.540985, region: "Grand Est", country: 'FR' },
    capacity_mw: 175,
    reservoir_volume: null,
    operator: null,
    river: null,
    commune: "Fessenheim",
    department: "Haut-Rhin",
    technology: "Fil de l'eau",
    head_m: 16.09,
    annual_generation_gwh: null,
    location_accuracy: "commune",
    official_name: "FESSENHEIM",
    source_date: "2025-09-30",
    verification_sources: ['Registre national RTE/ODRE (30/09/2025)', 'Base Adresse Nationale'],
    selection_reason: "Usine au fil de l’eau structurante >50 MW issue du registre national RTE/ODRE",
  },
  {
    id: 'hyd-official-caderousse',
    name: "Caderousse",
    type: 'hydro_production',
    subtype: 'run_of_river',
    location: { lat: 44.103315, lon: 4.757236, region: "Provence-Alpes-Côte d'Azur", country: 'FR' },
    capacity_mw: 156,
    reservoir_volume: null,
    operator: null,
    river: null,
    commune: "Caderousse",
    department: "Vaucluse",
    technology: "Fil de l'eau",
    head_m: 9.5,
    annual_generation_gwh: null,
    location_accuracy: "commune",
    official_name: "CADEROUSSE",
    source_date: "2025-09-30",
    verification_sources: ['Registre national RTE/ODRE (30/09/2025)', 'Base Adresse Nationale'],
    selection_reason: "Usine au fil de l’eau structurante >50 MW issue du registre national RTE/ODRE",
  },
  {
    id: 'hyd-official-la-saussaz-ii',
    name: "La Saussaz II",
    type: 'hydro_production',
    subtype: 'dam',
    location: { lat: 45.209415, lon: 6.484569, region: "Auvergne-Rhône-Alpes", country: 'FR' },
    capacity_mw: 145.4,
    reservoir_volume: null,
    operator: null,
    river: null,
    commune: "Saint-Michel-de-Maurienne",
    department: "Savoie",
    technology: "Eclusée",
    head_m: 212.5,
    annual_generation_gwh: null,
    location_accuracy: "commune",
    official_name: "SAUSSAZ II",
    source_date: "2025-09-30",
    verification_sources: ['Registre national RTE/ODRE (30/09/2025)', 'Base Adresse Nationale'],
    selection_reason: "Usine hydraulique de pointe >50 MW issue du registre national RTE/ODRE",
  },
  {
    id: 'hyd-official-saint-esteve-janson',
    name: "Saint-Estève-Janson",
    type: 'hydro_production',
    subtype: 'dam',
    location: { lat: 43.686330, lon: 5.392861, region: "Provence-Alpes-Côte d'Azur", country: 'FR' },
    capacity_mw: 141,
    reservoir_volume: null,
    operator: null,
    river: null,
    commune: "Saint-Estève-Janson",
    department: "Bouches-du-Rhône",
    technology: "Lac",
    head_m: 64,
    annual_generation_gwh: null,
    location_accuracy: "commune",
    official_name: "Saint-ESTEVE",
    source_date: "2025-09-30",
    verification_sources: ['Registre national RTE/ODRE (30/09/2025)', 'Base Adresse Nationale'],
    selection_reason: "Grand aménagement hydraulique >50 MW issu du registre national RTE/ODRE",
  },
  {
    id: 'hyd-official-logis-neuf',
    name: "Logis-Neuf",
    type: 'hydro_production',
    subtype: 'run_of_river',
    location: { lat: 44.664758, lon: 4.800936, region: "Auvergne-Rhône-Alpes", country: 'FR' },
    capacity_mw: 140,
    reservoir_volume: null,
    operator: null,
    river: null,
    commune: "Les Tourrettes",
    department: "Drôme",
    technology: "Fil de l'eau",
    head_m: 13.9,
    annual_generation_gwh: null,
    location_accuracy: "commune",
    official_name: "LOGIS-NEUF",
    source_date: "2025-09-30",
    verification_sources: ['Registre national RTE/ODRE (30/09/2025)', 'Base Adresse Nationale'],
    selection_reason: "Usine au fil de l’eau structurante >50 MW issue du registre national RTE/ODRE",
  },
  {
    id: 'hyd-official-gerstheim',
    name: "Gerstheim",
    type: 'hydro_production',
    subtype: 'run_of_river',
    location: { lat: 48.382501, lon: 7.696460, region: "Grand Est", country: 'FR' },
    capacity_mw: 139.4,
    reservoir_volume: null,
    operator: null,
    river: null,
    commune: "Gerstheim",
    department: "Bas-Rhin",
    technology: "Fil de l'eau",
    head_m: 11.4,
    annual_generation_gwh: null,
    location_accuracy: "commune",
    official_name: "GERSTHEIM",
    source_date: "2025-09-30",
    verification_sources: ['Registre national RTE/ODRE (30/09/2025)', 'Base Adresse Nationale'],
    selection_reason: "Usine au fil de l’eau structurante >50 MW issue du registre national RTE/ODRE",
  },
  {
    id: 'hyd-official-curbans',
    name: "Curbans",
    type: 'hydro_production',
    subtype: 'dam',
    location: { lat: 44.402669, lon: 5.082071, region: "Provence-Alpes-Côte d'Azur", country: 'FR' },
    capacity_mw: 139,
    reservoir_volume: null,
    operator: null,
    river: null,
    commune: "Venterol",
    department: "Alpes-de-Haute-Provence",
    technology: "Lac",
    head_m: 82.7,
    annual_generation_gwh: null,
    location_accuracy: "commune",
    official_name: "CURBANS",
    source_date: "2025-09-30",
    verification_sources: ['Registre national RTE/ODRE (30/09/2025)', 'Base Adresse Nationale'],
    selection_reason: "Grand aménagement hydraulique >50 MW issu du registre national RTE/ODRE",
  },
  {
    id: 'hyd-official-montpezat',
    name: "Montpezat",
    type: 'hydro_production',
    subtype: 'dam',
    location: { lat: 44.702766, lon: 4.230631, region: "Auvergne-Rhône-Alpes", country: 'FR' },
    capacity_mw: 131.8,
    reservoir_volume: null,
    operator: null,
    river: null,
    commune: "Montpezat-sous-Bauzon",
    department: "Ardèche",
    technology: "Lac",
    head_m: 634,
    annual_generation_gwh: null,
    location_accuracy: "site",
    official_name: "MONTPEZAT",
    source_date: "2025-09-30",
    verification_sources: ['Registre national RTE/ODRE (30/09/2025)', 'Base Adresse Nationale'],
    selection_reason: "Grand aménagement hydraulique >50 MW issu du registre national RTE/ODRE",
  },
  {
    id: 'hyd-official-hermillon',
    name: "Hermillon",
    type: 'hydro_production',
    subtype: 'dam',
    location: { lat: 45.305181, lon: 6.362977, region: "Auvergne-Rhône-Alpes", country: 'FR' },
    capacity_mw: 125.4,
    reservoir_volume: null,
    operator: null,
    river: null,
    commune: "La Tour-en-Maurienne",
    department: "Savoie",
    technology: "Eclusée",
    head_m: 166,
    annual_generation_gwh: null,
    location_accuracy: "commune",
    official_name: "HERMILLON",
    source_date: "2025-09-30",
    verification_sources: ['Registre national RTE/ODRE (30/09/2025)', 'Base Adresse Nationale'],
    selection_reason: "Usine hydraulique de pointe >50 MW issue du registre national RTE/ODRE",
  },
  {
    id: 'hyd-official-randens',
    name: "Randens",
    type: 'hydro_production',
    subtype: 'dam',
    location: { lat: 45.528300, lon: 6.320781, region: "Auvergne-Rhône-Alpes", country: 'FR' },
    capacity_mw: 124,
    reservoir_volume: null,
    operator: null,
    river: null,
    commune: "Val-d'Arc",
    department: "Savoie",
    technology: "Eclusée",
    head_m: 153.3,
    annual_generation_gwh: null,
    location_accuracy: "site",
    official_name: "RANDENS",
    source_date: "2025-09-30",
    verification_sources: ['Registre national RTE/ODRE (30/09/2025)', 'Base Adresse Nationale'],
    selection_reason: "Usine hydraulique de pointe >50 MW issue du registre national RTE/ODRE",
  },
  {
    id: 'hyd-official-combe-d-avrieux',
    name: "Combe d'Avrieux",
    type: 'hydro_production',
    subtype: 'dam',
    location: { lat: 45.216948, lon: 6.722039, region: "Auvergne-Rhône-Alpes", country: 'FR' },
    capacity_mw: 122,
    reservoir_volume: null,
    operator: null,
    river: null,
    commune: "Avrieux",
    department: "Savoie",
    technology: "Lac",
    head_m: 859.71,
    annual_generation_gwh: null,
    location_accuracy: "commune",
    official_name: "COMBE D AVRIEUX",
    source_date: "2025-09-30",
    verification_sources: ['Registre national RTE/ODRE (30/09/2025)', 'Base Adresse Nationale'],
    selection_reason: "Grand aménagement hydraulique >50 MW issu du registre national RTE/ODRE",
  },
  {
    id: 'hyd-official-saint-pierre',
    name: "Saint-Pierre",
    type: 'hydro_production',
    subtype: 'dam',
    location: { lat: 45.391261, lon: 2.366012, region: "Auvergne-Rhône-Alpes", country: 'FR' },
    capacity_mw: 120.2,
    reservoir_volume: null,
    operator: null,
    river: null,
    commune: "Saint-Pierre",
    department: "Cantal",
    technology: "Eclusée",
    head_m: 75,
    annual_generation_gwh: null,
    location_accuracy: "site",
    official_name: "Saint-PIERRE-MAREGES",
    source_date: "2025-09-30",
    verification_sources: ['Registre national RTE/ODRE (30/09/2025)', 'Base Adresse Nationale'],
    selection_reason: "Usine hydraulique de pointe >50 MW issue du registre national RTE/ODRE",
  },
  {
    id: 'hyd-official-pied-de-borne',
    name: "Pied-de-Borne",
    type: 'hydro_production',
    subtype: 'dam',
    location: { lat: 44.482903, lon: 3.962328, region: "Occitanie", country: 'FR' },
    capacity_mw: 109.4,
    reservoir_volume: null,
    operator: null,
    river: null,
    commune: "Pied-de-Borne",
    department: "Lozère",
    technology: "Lac",
    head_m: 292,
    annual_generation_gwh: null,
    location_accuracy: "site",
    official_name: "PIED-DE-BORNE",
    source_date: "2025-09-30",
    verification_sources: ['Registre national RTE/ODRE (30/09/2025)', 'Base Adresse Nationale'],
    selection_reason: "Grand aménagement hydraulique >50 MW issu du registre national RTE/ODRE",
  },
  {
    id: 'hyd-official-saint-pierre-cognet',
    name: "Saint-Pierre-Cognet",
    type: 'hydro_production',
    subtype: 'dam',
    location: { lat: 44.872582, lon: 5.772941, region: "Auvergne-Rhône-Alpes", country: 'FR' },
    capacity_mw: 101,
    reservoir_volume: null,
    operator: null,
    river: null,
    commune: "Saint-Jean-d'Hérans",
    department: "Isère",
    technology: "Eclusée",
    head_m: 90,
    annual_generation_gwh: null,
    location_accuracy: "commune",
    official_name: "Saint-PIERRE-COGNET",
    source_date: "2025-09-30",
    verification_sources: ['Registre national RTE/ODRE (30/09/2025)', 'Base Adresse Nationale'],
    selection_reason: "Usine hydraulique de pointe >50 MW issue du registre national RTE/ODRE",
  },
  {
    id: 'hyd-official-laval-de-cere-ii',
    name: "Laval-De-Cere Ii",
    type: 'hydro_production',
    subtype: 'dam',
    location: { lat: 44.981587, lon: 1.989847, region: "Nouvelle-Aquitaine", country: 'FR' },
    capacity_mw: 95.7,
    reservoir_volume: null,
    operator: null,
    river: null,
    commune: "Camps-Saint-Mathurin-Léobazel",
    department: "Corrèze",
    technology: "Eclusée",
    head_m: 276.5,
    annual_generation_gwh: null,
    location_accuracy: "commune",
    official_name: "LAVAL-DE-CERE II",
    source_date: "2025-09-30",
    verification_sources: ['Registre national RTE/ODRE (30/09/2025)', 'Base Adresse Nationale'],
    selection_reason: "Usine hydraulique de pointe >50 MW issue du registre national RTE/ODRE",
  },
  {
    id: 'hyd-official-gavet',
    name: "Gavet",
    type: 'hydro_production',
    subtype: 'run_of_river',
    location: { lat: 45.068513, lon: 5.870894, region: "Auvergne-Rhône-Alpes", country: 'FR' },
    capacity_mw: 93,
    reservoir_volume: null,
    operator: null,
    river: null,
    commune: "Livet-et-Gavet",
    department: "Isère",
    technology: "Fil de l'eau",
    head_m: 268,
    annual_generation_gwh: null,
    location_accuracy: "commune",
    official_name: "GAVET (HYDRAULIQUE)",
    source_date: "2025-09-30",
    verification_sources: ['Registre national RTE/ODRE (30/09/2025)', 'Base Adresse Nationale'],
    selection_reason: "Actif hydraulique >50 MW issu du registre national RTE/ODRE",
  },
  {
    id: 'hyd-official-mallemort',
    name: "Mallemort",
    type: 'hydro_production',
    subtype: 'dam',
    location: { lat: 43.725577, lon: 5.179513, region: "Provence-Alpes-Côte d'Azur", country: 'FR' },
    capacity_mw: 93,
    reservoir_volume: null,
    operator: null,
    river: null,
    commune: "Mallemort",
    department: "Bouches-du-Rhône",
    technology: "Lac",
    head_m: 44.1,
    annual_generation_gwh: null,
    location_accuracy: "commune",
    official_name: "MALLEMORT",
    source_date: "2025-09-30",
    verification_sources: ['Registre national RTE/ODRE (30/09/2025)', 'Base Adresse Nationale'],
    selection_reason: "Grand aménagement hydraulique >50 MW issu du registre national RTE/ODRE",
  },
  {
    id: 'hyd-official-chautagne',
    name: "Chautagne",
    type: 'hydro_production',
    subtype: 'run_of_river',
    location: { lat: 45.894806, lon: 5.806284, region: "Auvergne-Rhône-Alpes", country: 'FR' },
    capacity_mw: 91.6,
    reservoir_volume: null,
    operator: null,
    river: null,
    commune: "Anglefort",
    department: "Ain",
    technology: "Fil de l'eau",
    head_m: 17,
    annual_generation_gwh: null,
    location_accuracy: "commune",
    official_name: "CHAUTAGNE",
    source_date: "2025-09-30",
    verification_sources: ['Registre national RTE/ODRE (30/09/2025)', 'Base Adresse Nationale'],
    selection_reason: "Actif hydraulique >50 MW issu du registre national RTE/ODRE",
  },
  {
    id: 'hyd-official-brens',
    name: "Brens",
    type: 'hydro_production',
    subtype: 'run_of_river',
    location: { lat: 45.725811, lon: 5.710929, region: "Auvergne-Rhône-Alpes", country: 'FR' },
    capacity_mw: 90,
    reservoir_volume: null,
    operator: null,
    river: null,
    commune: "Virignin",
    department: "Ain",
    technology: "Fil de l'eau",
    head_m: 18,
    annual_generation_gwh: null,
    location_accuracy: "commune",
    official_name: "BRENS",
    source_date: "2025-09-30",
    verification_sources: ['Registre national RTE/ODRE (30/09/2025)', 'Base Adresse Nationale'],
    selection_reason: "Actif hydraulique >50 MW issu du registre national RTE/ODRE",
  },
  {
    id: 'hyd-official-aussois',
    name: "Aussois",
    type: 'hydro_production',
    subtype: 'dam',
    location: { lat: 45.215791, lon: 6.721873, region: "Auvergne-Rhône-Alpes", country: 'FR' },
    capacity_mw: 87,
    reservoir_volume: null,
    operator: null,
    river: null,
    commune: "Avrieux",
    department: "Savoie",
    technology: "Lac",
    head_m: 861.2,
    annual_generation_gwh: null,
    location_accuracy: "commune",
    official_name: "AUSSOIS",
    source_date: "2025-09-30",
    verification_sources: ['Registre national RTE/ODRE (30/09/2025)', 'Base Adresse Nationale'],
    selection_reason: "Grand aménagement hydraulique >50 MW issu du registre national RTE/ODRE",
  },
  {
    id: 'hyd-official-pierre-benite',
    name: "Pierre-Bénite",
    type: 'hydro_production',
    subtype: 'run_of_river',
    location: { lat: 45.701914, lon: 4.855418, region: "Auvergne-Rhône-Alpes", country: 'FR' },
    capacity_mw: 80.8,
    reservoir_volume: null,
    operator: null,
    river: null,
    commune: "Saint-Fons",
    department: "Rhône",
    technology: "Fil de l'eau",
    head_m: 11.7,
    annual_generation_gwh: null,
    location_accuracy: "commune",
    official_name: "PIERRE-BENITE",
    source_date: "2025-09-30",
    verification_sources: ['Registre national RTE/ODRE (30/09/2025)', 'Base Adresse Nationale'],
    selection_reason: "Actif hydraulique >50 MW issu du registre national RTE/ODRE",
  },
  {
    id: 'hyd-official-sablons',
    name: "Sablons",
    type: 'hydro_production',
    subtype: 'run_of_river',
    location: { lat: 45.317697, lon: 4.771892, region: "Auvergne-Rhône-Alpes", country: 'FR' },
    capacity_mw: 80.7,
    reservoir_volume: null,
    operator: null,
    river: null,
    commune: "Sablons",
    department: "Isère",
    technology: "Fil de l'eau",
    head_m: 15.3,
    annual_generation_gwh: null,
    location_accuracy: "commune",
    official_name: "SABLONS",
    source_date: "2025-09-30",
    verification_sources: ['Registre national RTE/ODRE (30/09/2025)', 'Base Adresse Nationale'],
    selection_reason: "Actif hydraulique >50 MW issu du registre national RTE/ODRE",
  },
  {
    id: 'hyd-official-salignac',
    name: "Salignac",
    type: 'hydro_production',
    subtype: 'dam',
    location: { lat: 44.149747, lon: 5.971265, region: "Provence-Alpes-Côte d'Azur", country: 'FR' },
    capacity_mw: 78,
    reservoir_volume: null,
    operator: null,
    river: null,
    commune: "Salignac",
    department: "Alpes-de-Haute-Provence",
    technology: "Lac",
    head_m: 29.5,
    annual_generation_gwh: null,
    location_accuracy: "commune",
    official_name: "SALIGNAC",
    source_date: "2025-09-30",
    verification_sources: ['Registre national RTE/ODRE (30/09/2025)', 'Base Adresse Nationale'],
    selection_reason: "Grand aménagement hydraulique >50 MW issu du registre national RTE/ODRE",
  },
  {
    id: 'hyd-official-le-sautet',
    name: "Le Sautet",
    type: 'hydro_production',
    subtype: 'dam',
    location: { lat: 44.796199, lon: 5.903996, region: "Auvergne-Rhône-Alpes", country: 'FR' },
    capacity_mw: 76.5,
    reservoir_volume: null,
    operator: null,
    river: null,
    commune: "Pellafol",
    department: "Isère",
    technology: "Lac",
    head_m: 93.85,
    annual_generation_gwh: null,
    location_accuracy: "commune",
    official_name: "SAUTET",
    source_date: "2025-09-30",
    verification_sources: ['Registre national RTE/ODRE (30/09/2025)', 'Base Adresse Nationale'],
    selection_reason: "Grand aménagement hydraulique >50 MW issu du registre national RTE/ODRE",
  },
  {
    id: 'hyd-official-luz-luz',
    name: "Luz Luz",
    type: 'hydro_production',
    subtype: 'dam',
    location: { lat: 42.870562, lon: -0.013993, region: "Occitanie", country: 'FR' },
    capacity_mw: 71.7,
    reservoir_volume: null,
    operator: null,
    river: null,
    commune: "Sassis",
    department: "Hautes-Pyrénées",
    technology: "Lac",
    head_m: 320.05,
    annual_generation_gwh: null,
    location_accuracy: "site",
    official_name: "LUZ H-CENTRALE HYDRAULIQUE DE LUZ",
    source_date: "2025-09-30",
    verification_sources: ['Registre national RTE/ODRE (30/09/2025)', 'Base Adresse Nationale'],
    selection_reason: "Grand aménagement hydraulique >50 MW issu du registre national RTE/ODRE",
  },
  {
    id: 'hyd-official-orelle',
    name: "Orelle",
    type: 'hydro_production',
    subtype: 'run_of_river',
    location: { lat: 45.211743, lon: 6.546913, region: "Auvergne-Rhône-Alpes", country: 'FR' },
    capacity_mw: 71.68,
    reservoir_volume: null,
    operator: null,
    river: null,
    commune: "Orelle",
    department: "Savoie",
    technology: "Fil de l'eau",
    head_m: 118.6,
    annual_generation_gwh: null,
    location_accuracy: "site",
    official_name: "ORELLE",
    source_date: "2025-09-30",
    verification_sources: ['Registre national RTE/ODRE (30/09/2025)', 'Base Adresse Nationale'],
    selection_reason: "Actif hydraulique >50 MW issu du registre national RTE/ODRE",
  },
  {
    id: 'hyd-official-eguzon',
    name: "Éguzon",
    type: 'hydro_production',
    subtype: 'dam',
    location: { lat: 46.443039, lon: 1.580935, region: "Centre-Val de Loire", country: 'FR' },
    capacity_mw: 71.6,
    reservoir_volume: null,
    operator: null,
    river: null,
    commune: "Éguzon-Chantôme",
    department: "Indre",
    technology: "Eclusée",
    head_m: 54.87,
    annual_generation_gwh: null,
    location_accuracy: "commune",
    official_name: "EGUZON",
    source_date: "2025-09-30",
    verification_sources: ['Registre national RTE/ODRE (30/09/2025)', 'Base Adresse Nationale'],
    selection_reason: "Usine hydraulique de pointe >50 MW issue du registre national RTE/ODRE",
  },
  {
    id: 'hyd-official-jouques',
    name: "Jouques",
    type: 'hydro_production',
    subtype: 'dam',
    location: { lat: 43.668486, lon: 5.674397, region: "Provence-Alpes-Côte d'Azur", country: 'FR' },
    capacity_mw: 71.5,
    reservoir_volume: null,
    operator: null,
    river: null,
    commune: "Jouques",
    department: "Bouches-du-Rhône",
    technology: "Lac",
    head_m: 30.75,
    annual_generation_gwh: null,
    location_accuracy: "commune",
    official_name: "JOUQUES",
    source_date: "2025-09-30",
    verification_sources: ['Registre national RTE/ODRE (30/09/2025)', 'Base Adresse Nationale'],
    selection_reason: "Grand aménagement hydraulique >50 MW issu du registre national RTE/ODRE",
  },
  {
    id: 'hyd-official-bregnier-cordon',
    name: "Bregnier-Cordon",
    type: 'hydro_production',
    subtype: 'run_of_river',
    location: { lat: 45.643389, lon: 5.621221, region: "Auvergne-Rhône-Alpes", country: 'FR' },
    capacity_mw: 70.4,
    reservoir_volume: null,
    operator: null,
    river: null,
    commune: "Brégnier-Cordon",
    department: "Ain",
    technology: "Fil de l'eau",
    head_m: 13.7,
    annual_generation_gwh: null,
    location_accuracy: "commune",
    official_name: "BREGNIER-CORDON",
    source_date: "2025-09-30",
    verification_sources: ['Registre national RTE/ODRE (30/09/2025)', 'Base Adresse Nationale'],
    selection_reason: "Actif hydraulique >50 MW issu du registre national RTE/ODRE",
  },
  {
    id: 'hyd-official-golfech',
    name: "Golfech",
    type: 'hydro_production',
    subtype: 'run_of_river',
    location: { lat: 44.120852, lon: 0.873236, region: "Occitanie", country: 'FR' },
    capacity_mw: 69,
    reservoir_volume: null,
    operator: null,
    river: null,
    commune: "Golfech",
    department: "Tarn-et-Garonne",
    technology: "Fil de l'eau",
    head_m: 17,
    annual_generation_gwh: null,
    location_accuracy: "commune",
    official_name: "GOLFECH",
    source_date: "2025-09-30",
    verification_sources: ['Registre national RTE/ODRE (30/09/2025)', 'Base Adresse Nationale'],
    selection_reason: "Actif hydraulique >50 MW issu du registre national RTE/ODRE",
  },
  {
    id: 'hyd-official-villerest',
    name: "Villerest",
    type: 'hydro_production',
    subtype: 'run_of_river',
    location: { lat: 46.002149, lon: 4.062469, region: "Auvergne-Rhône-Alpes", country: 'FR' },
    capacity_mw: 65.76,
    reservoir_volume: null,
    operator: null,
    river: null,
    commune: "Commelle-Vernay",
    department: "Loire",
    technology: "Fil de l'eau",
    head_m: 46,
    annual_generation_gwh: null,
    location_accuracy: "commune",
    official_name: "VILLEREST",
    source_date: "2025-09-30",
    verification_sources: ['Registre national RTE/ODRE (30/09/2025)', 'Base Adresse Nationale'],
    selection_reason: "Actif hydraulique >50 MW issu du registre national RTE/ODRE",
  },
  {
    id: 'hyd-official-brevieres',
    name: "Brevieres",
    type: 'hydro_production',
    subtype: 'dam',
    location: { lat: 45.509317, lon: 6.921354, region: "Auvergne-Rhône-Alpes", country: 'FR' },
    capacity_mw: 64,
    reservoir_volume: null,
    operator: null,
    river: null,
    commune: "Tignes",
    department: "Savoie",
    technology: "Lac",
    head_m: 233.5,
    annual_generation_gwh: null,
    location_accuracy: "commune",
    official_name: "BREVIERES",
    source_date: "2025-09-30",
    verification_sources: ['Registre national RTE/ODRE (30/09/2025)', 'Base Adresse Nationale'],
    selection_reason: "Grand aménagement hydraulique >50 MW issu du registre national RTE/ODRE",
  },
  {
    id: 'hyd-official-salon',
    name: "Salon",
    type: 'hydro_production',
    subtype: 'dam',
    location: { lat: 43.637700, lon: 5.062036, region: "Provence-Alpes-Côte d'Azur", country: 'FR' },
    capacity_mw: 64,
    reservoir_volume: null,
    operator: null,
    river: null,
    commune: "Salon-de-Provence",
    department: "Bouches-du-Rhône",
    technology: "Lac",
    head_m: 44.5,
    annual_generation_gwh: null,
    location_accuracy: "commune",
    official_name: "SALON",
    source_date: "2025-09-30",
    verification_sources: ['Registre national RTE/ODRE (30/09/2025)', 'Base Adresse Nationale'],
    selection_reason: "Grand aménagement hydraulique >50 MW issu du registre national RTE/ODRE",
  },
  {
    id: 'hyd-official-peyrat-le-chateau',
    name: "Peyrat-Le-Chateau",
    type: 'hydro_production',
    subtype: 'dam',
    location: { lat: 45.827391, lon: 1.775264, region: "Nouvelle-Aquitaine", country: 'FR' },
    capacity_mw: 63.5,
    reservoir_volume: null,
    operator: null,
    river: null,
    commune: "Peyrat-le-Château",
    department: "Haute-Vienne",
    technology: "Lac",
    head_m: 252,
    annual_generation_gwh: null,
    location_accuracy: "commune",
    official_name: "PEYRAT-LE-CHATEAU",
    source_date: "2025-09-30",
    verification_sources: ['Registre national RTE/ODRE (30/09/2025)', 'Base Adresse Nationale'],
    selection_reason: "Grand aménagement hydraulique >50 MW issu du registre national RTE/ODRE",
  },
  {
    id: 'hyd-official-vaugris',
    name: "Vaugris",
    type: 'hydro_production',
    subtype: 'run_of_river',
    location: { lat: 45.493992, lon: 4.834583, region: "Auvergne-Rhône-Alpes", country: 'FR' },
    capacity_mw: 61,
    reservoir_volume: null,
    operator: null,
    river: null,
    commune: "Reventin-Vaugris",
    department: "Isère",
    technology: "Fil de l'eau",
    head_m: 6.8,
    annual_generation_gwh: null,
    location_accuracy: "commune",
    official_name: "VAUGRIS",
    source_date: "2025-09-30",
    verification_sources: ['Registre national RTE/ODRE (30/09/2025)', 'Base Adresse Nationale'],
    selection_reason: "Actif hydraulique >50 MW issu du registre national RTE/ODRE",
  },
  {
    id: 'hyd-official-saint-georges-de-commiers',
    name: "Saint-Georges-De-Commiers",
    type: 'hydro_production',
    subtype: 'dam',
    location: { lat: 45.008165, lon: 5.689281, region: "Auvergne-Rhône-Alpes", country: 'FR' },
    capacity_mw: 60.8,
    reservoir_volume: null,
    operator: null,
    river: null,
    commune: "Saint-Georges-de-Commiers",
    department: "Isère",
    technology: "Eclusée",
    head_m: 82.45,
    annual_generation_gwh: null,
    location_accuracy: "site",
    official_name: "Saint-GEORGES-DE-COMMIERS",
    source_date: "2025-09-30",
    verification_sources: ['Registre national RTE/ODRE (30/09/2025)', 'Base Adresse Nationale'],
    selection_reason: "Usine hydraulique de pointe >50 MW issue du registre national RTE/ODRE",
  },
  {
    id: 'hyd-official-gervans',
    name: "Gervans",
    type: 'hydro_production',
    subtype: 'run_of_river',
    location: { lat: 45.107858, lon: 4.831639, region: "Auvergne-Rhône-Alpes", country: 'FR' },
    capacity_mw: 58,
    reservoir_volume: null,
    operator: null,
    river: null,
    commune: "Gervans",
    department: "Drôme",
    technology: "Fil de l'eau",
    head_m: 11.4,
    annual_generation_gwh: null,
    location_accuracy: "commune",
    official_name: "GERVANS",
    source_date: "2025-09-30",
    verification_sources: ['Registre national RTE/ODRE (30/09/2025)', 'Base Adresse Nationale'],
    selection_reason: "Actif hydraulique >50 MW issu du registre national RTE/ODRE",
  },
  {
    id: 'hyd-official-saint-guillerme',
    name: "Saint-Guillerme",
    type: 'hydro_production',
    subtype: 'dam',
    location: { lat: 45.030818, lon: 6.078754, region: "Auvergne-Rhône-Alpes", country: 'FR' },
    capacity_mw: 58,
    reservoir_volume: null,
    operator: null,
    river: null,
    commune: "Auris",
    department: "Isère",
    technology: "Lac",
    head_m: 293,
    annual_generation_gwh: null,
    location_accuracy: "site",
    official_name: "Saint-GUILLERME",
    source_date: "2025-09-30",
    verification_sources: ['Registre national RTE/ODRE (30/09/2025)', 'Base Adresse Nationale'],
    selection_reason: "Grand aménagement hydraulique >50 MW issu du registre national RTE/ODRE",
  },
  {
    id: 'hyd-official-cordeac',
    name: "Cordeac",
    type: 'hydro_production',
    subtype: 'dam',
    location: { lat: 44.826359, lon: 5.838966, region: "Auvergne-Rhône-Alpes", country: 'FR' },
    capacity_mw: 57.4,
    reservoir_volume: null,
    operator: null,
    river: null,
    commune: "Châtel-en-Trièves",
    department: "Isère",
    technology: "Lac",
    head_m: 91.15,
    annual_generation_gwh: null,
    location_accuracy: "commune",
    official_name: "CORDEAC",
    source_date: "2025-09-30",
    verification_sources: ['Registre national RTE/ODRE (30/09/2025)', 'Base Adresse Nationale'],
    selection_reason: "Grand aménagement hydraulique >50 MW issu du registre national RTE/ODRE",
  },
  {
    id: 'hyd-official-nentilla',
    name: "Nentilla",
    type: 'hydro_production',
    subtype: 'dam',
    location: { lat: 42.749711, lon: 2.234726, region: "Occitanie", country: 'FR' },
    capacity_mw: 54,
    reservoir_volume: null,
    operator: null,
    river: null,
    commune: "Sainte-Colombe-sur-Guette",
    department: "Aude",
    technology: "Lac",
    head_m: 526.6,
    annual_generation_gwh: null,
    location_accuracy: "commune",
    official_name: "NENTILLA",
    source_date: "2025-09-30",
    verification_sources: ['Registre national RTE/ODRE (30/09/2025)', 'Base Adresse Nationale'],
    selection_reason: "Grand aménagement hydraulique >50 MW issu du registre national RTE/ODRE",
  },
  {
    id: 'hyd-official-sainte-tulle-2-g5-prod',
    name: "Sainte-Tulle 2 (g5 Prod)",
    type: 'hydro_production',
    subtype: 'dam',
    location: { lat: 43.796441, lon: 5.780523, region: "Provence-Alpes-Côte d'Azur", country: 'FR' },
    capacity_mw: 52.31,
    reservoir_volume: null,
    operator: null,
    river: null,
    commune: "Sainte-Tulle",
    department: "Alpes-de-Haute-Provence",
    technology: "Lac",
    head_m: 38.57,
    annual_generation_gwh: null,
    location_accuracy: "commune",
    official_name: "SAINTE-TULLE 2 (G5 PROD)",
    source_date: "2025-09-30",
    verification_sources: ['Registre national RTE/ODRE (30/09/2025)', 'Base Adresse Nationale'],
    selection_reason: "Grand aménagement hydraulique >50 MW issu du registre national RTE/ODRE",
  },
  {
    id: 'hyd-official-saint-martin-vesubie',
    name: "Saint-Martin-Vesubie",
    type: 'hydro_production',
    subtype: 'dam',
    location: { lat: 44.071816, lon: 7.258186, region: "Provence-Alpes-Côte d'Azur", country: 'FR' },
    capacity_mw: 52.1,
    reservoir_volume: null,
    operator: null,
    river: null,
    commune: "Saint-Martin-Vésubie",
    department: "Alpes-Maritimes",
    technology: "Eclusée",
    head_m: 730.85,
    annual_generation_gwh: null,
    location_accuracy: "commune",
    official_name: "Saint-MARTIN-VESUBIE",
    source_date: "2025-09-30",
    verification_sources: ['Registre national RTE/ODRE (30/09/2025)', 'Base Adresse Nationale'],
    selection_reason: "Usine hydraulique de pointe >50 MW issue du registre national RTE/ODRE",
  },
  {
    id: 'hyd-official-passy',
    name: "Passy",
    type: 'hydro_production',
    subtype: 'run_of_river',
    location: { lat: 45.922394, lon: 6.721547, region: "Auvergne-Rhône-Alpes", country: 'FR' },
    capacity_mw: 52,
    reservoir_volume: null,
    operator: null,
    river: null,
    commune: "Passy",
    department: "Haute-Savoie",
    technology: "Fil de l'eau",
    head_m: 387.5,
    annual_generation_gwh: null,
    location_accuracy: "site",
    official_name: "PASSY",
    source_date: "2025-09-30",
    verification_sources: ['Registre national RTE/ODRE (30/09/2025)', 'Base Adresse Nationale'],
    selection_reason: "Actif hydraulique >50 MW issu du registre national RTE/ODRE",
  },
  {
    id: 'hyd-official-sauveterre',
    name: "Sauveterre",
    type: 'hydro_production',
    subtype: 'run_of_river',
    location: { lat: 43.975228, lon: 4.778459, region: "Occitanie", country: 'FR' },
    capacity_mw: 52,
    reservoir_volume: null,
    operator: null,
    river: null,
    commune: "Villeneuve-lès-Avignon",
    department: "Gard",
    technology: "Fil de l'eau",
    head_m: 9.4,
    annual_generation_gwh: null,
    location_accuracy: "commune",
    official_name: "SAUVETERRE",
    source_date: "2025-09-30",
    verification_sources: ['Registre national RTE/ODRE (30/09/2025)', 'Base Adresse Nationale'],
    selection_reason: "Actif hydraulique >50 MW issu du registre national RTE/ODRE",
  },
  {
    id: 'hyd-official-pont-escoffier',
    name: "Pont-Escoffier",
    type: 'hydro_production',
    subtype: 'run_of_river',
    location: { lat: 45.002031, lon: 6.069475, region: "Auvergne-Rhône-Alpes", country: 'FR' },
    capacity_mw: 51.3,
    reservoir_volume: null,
    operator: null,
    river: null,
    commune: "Le Bourg-d'Oisans",
    department: "Isère",
    technology: "Fil de l'eau",
    head_m: 401.65,
    annual_generation_gwh: null,
    location_accuracy: "commune",
    official_name: "PONT-ESCOFFIER",
    source_date: "2025-09-30",
    verification_sources: ['Registre national RTE/ODRE (30/09/2025)', 'Base Adresse Nationale'],
    selection_reason: "Actif hydraulique >50 MW issu du registre national RTE/ODRE",
  },
  {
    id: 'hyd-official-soulom',
    name: "Soulom",
    type: 'hydro_production',
    subtype: 'run_of_river',
    location: { lat: 42.958045, lon: -0.070034, region: "Occitanie", country: 'FR' },
    capacity_mw: 51,
    reservoir_volume: null,
    operator: null,
    river: null,
    commune: "Soulom",
    department: "Hautes-Pyrénées",
    technology: "Fil de l'eau",
    head_m: 265,
    annual_generation_gwh: null,
    location_accuracy: "commune",
    official_name: "SOULOM",
    source_date: "2025-09-30",
    verification_sources: ['Registre national RTE/ODRE (30/09/2025)', 'Base Adresse Nationale'],
    selection_reason: "Actif hydraulique >50 MW issu du registre national RTE/ODRE",
  }
] satisfies HydraulicBackboneSeed[];
