/**
 * hydraulic-backbone.ts — Sélection volontairement restreinte d'actifs hydrauliques critiques.
 * Non exhaustive par design. Priorité aux STEP, grands barrages, réservoirs systémiques
 * et quelques actifs insulaires / DROM à forte valeur OSINT.
 */

import type {
  HydraulicAssetSubtype,
  HydraulicAssetType,
  HydraulicLocationAccuracy,
} from '../types/index.ts';
import { HYDRAULIC_OFFICIAL_BACKBONE_SEEDS } from './hydraulic-backbone-official.ts';

export interface HydraulicBackboneSeed {
  id: string;
  name: string;
  type: HydraulicAssetType;
  subtype: HydraulicAssetSubtype;
  location: {
    lat: number;
    lon: number;
    region: string;
    country: 'FR';
  };
  capacity_mw: number | null;
  reservoir_volume: number | null;
  operator: string | null;
  river: string | null;
  commune?: string | null;
  department?: string | null;
  technology?: string | null;
  head_m?: number | null;
  annual_generation_gwh?: number | null;
  location_accuracy?: HydraulicLocationAccuracy;
  official_name?: string | null;
  source_date?: string | null;
  verification_sources?: string[];
  selection_reason: string;
}

export const HYDRAULIC_MANUAL_BACKBONE_SEEDS: HydraulicBackboneSeed[] = [
  {
    id: 'hyd-grand-maison',
    name: 'Grand Maison',
    type: 'step_storage',
    subtype: 'pumped_storage',
    location: { lat: 45.227, lon: 6.086, region: 'Auvergne-Rhône-Alpes', country: 'FR' },
    capacity_mw: 1800,
    reservoir_volume: 140,
    operator: 'EDF',
    river: "Eau d'Olle",
    selection_reason: 'STEP majeure du système français',
  },
  {
    id: 'hyd-super-bissorte',
    name: 'Super-Bissorte',
    type: 'step_storage',
    subtype: 'pumped_storage',
    location: { lat: 45.272, lon: 6.699, region: 'Auvergne-Rhône-Alpes', country: 'FR' },
    capacity_mw: 748,
    reservoir_volume: 39,
    operator: 'EDF',
    river: 'Arc',
    selection_reason: 'STEP structurante de la Maurienne',
  },
  {
    id: 'hyd-la-coche',
    name: 'La Coche',
    type: 'step_storage',
    subtype: 'pumped_storage',
    location: { lat: 45.522, lon: 6.649, region: 'Auvergne-Rhône-Alpes', country: 'FR' },
    capacity_mw: 330,
    reservoir_volume: 13,
    operator: 'EDF',
    river: 'Isère',
    selection_reason: 'STEP alpine de flexibilité réseau',
  },
  {
    id: 'hyd-roselend-la-bathie',
    name: 'Roselend - La Bâthie',
    type: 'hydro_production',
    subtype: 'dam',
    location: { lat: 45.692, lon: 6.636, region: 'Auvergne-Rhône-Alpes', country: 'FR' },
    capacity_mw: 550,
    reservoir_volume: 187,
    operator: 'EDF',
    river: 'Doron de Beaufort',
    selection_reason: 'Complexe alpin à forte retenue',
  },
  {
    id: 'hyd-malgovert',
    name: 'Malgovert',
    type: 'hydro_production',
    subtype: 'dam',
    location: { lat: 45.62, lon: 6.77, region: 'Auvergne-Rhône-Alpes', country: 'FR' },
    capacity_mw: 300,
    reservoir_volume: null,
    operator: 'EDF',
    river: 'Isère',
    selection_reason: 'Usine haute chute stratégique Tarentaise',
  },
  {
    id: 'hyd-monteynard-avignonet',
    name: 'Monteynard-Avignonet',
    type: 'hydro_production',
    subtype: 'dam',
    location: { lat: 44.879, lon: 5.666, region: 'Auvergne-Rhône-Alpes', country: 'FR' },
    capacity_mw: 360,
    reservoir_volume: 240,
    operator: 'EDF',
    river: 'Drac',
    selection_reason: 'Réservoir alpin systémique pour le Sud-Est',
  },
  {
    id: 'hyd-genissiat',
    name: 'Génissiat',
    type: 'hydro_production',
    subtype: 'dam',
    location: { lat: 46.082, lon: 5.807, region: 'Auvergne-Rhône-Alpes', country: 'FR' },
    capacity_mw: 420,
    reservoir_volume: 53,
    operator: 'CNR',
    river: 'Rhône',
    selection_reason: 'Grand barrage du Rhône à impact régional fort',
  },
  {
    id: 'hyd-vouglans',
    name: 'Vouglans',
    type: 'hydro_production',
    subtype: 'dam',
    location: { lat: 46.706, lon: 5.671, region: 'Bourgogne-Franche-Comté', country: 'FR' },
    capacity_mw: 285,
    reservoir_volume: 605,
    operator: 'EDF',
    river: 'Ain',
    selection_reason: 'Réservoir majeur et actif hydro critique',
  },
  {
    id: 'hyd-revin',
    name: 'Revin',
    type: 'step_storage',
    subtype: 'pumped_storage',
    location: { lat: 49.942, lon: 4.64, region: 'Grand Est', country: 'FR' },
    capacity_mw: 800,
    reservoir_volume: null,
    operator: 'EDF',
    river: 'Meuse',
    selection_reason: 'STEP du Grand Est, pivot de flexibilité',
  },
  {
    id: 'hyd-kembs',
    name: 'Kembs',
    type: 'hydro_production',
    subtype: 'run_of_river',
    location: { lat: 47.744, lon: 7.515, region: 'Grand Est', country: 'FR' },
    capacity_mw: 160,
    reservoir_volume: null,
    operator: 'EDF',
    river: 'Rhin',
    selection_reason: 'Chaîne rhénane structurante',
  },
  {
    id: 'hyd-ottmarsheim',
    name: 'Ottmarsheim',
    type: 'hydro_production',
    subtype: 'run_of_river',
    location: { lat: 47.804, lon: 7.509, region: 'Grand Est', country: 'FR' },
    capacity_mw: 172,
    reservoir_volume: null,
    operator: 'EDF',
    river: 'Rhin',
    selection_reason: 'Chaîne rhénane structurante',
  },
  {
    id: 'hyd-vogelgrun',
    name: 'Vogelgrun',
    type: 'hydro_production',
    subtype: 'run_of_river',
    location: { lat: 48.016, lon: 7.564, region: 'Grand Est', country: 'FR' },
    capacity_mw: 140,
    reservoir_volume: null,
    operator: 'EDF',
    river: 'Rhin',
    selection_reason: 'Chaîne rhénane structurante',
  },
  {
    id: 'hyd-marckolsheim',
    name: 'Marckolsheim',
    type: 'hydro_production',
    subtype: 'run_of_river',
    location: { lat: 48.164, lon: 7.544, region: 'Grand Est', country: 'FR' },
    capacity_mw: 148,
    reservoir_volume: null,
    operator: 'EDF',
    river: 'Rhin',
    selection_reason: 'Chaîne rhénane structurante',
  },
  {
    id: 'hyd-rhinau',
    name: 'Rhinau',
    type: 'hydro_production',
    subtype: 'run_of_river',
    location: { lat: 48.336, lon: 7.703, region: 'Grand Est', country: 'FR' },
    capacity_mw: 140,
    reservoir_volume: null,
    operator: 'EDF',
    river: 'Rhin',
    selection_reason: 'Chaîne rhénane structurante',
  },
  {
    id: 'hyd-strasbourg',
    name: 'Strasbourg',
    type: 'hydro_production',
    subtype: 'run_of_river',
    location: { lat: 48.569, lon: 7.789, region: 'Grand Est', country: 'FR' },
    capacity_mw: 148,
    reservoir_volume: null,
    operator: 'EDF',
    river: 'Rhin',
    selection_reason: 'Chaîne rhénane structurante',
  },
  {
    id: 'hyd-gambsheim',
    name: 'Gambsheim',
    type: 'hydro_production',
    subtype: 'run_of_river',
    location: { lat: 48.693, lon: 8.013, region: 'Grand Est', country: 'FR' },
    capacity_mw: 140,
    reservoir_volume: null,
    operator: 'EDF',
    river: 'Rhin',
    selection_reason: 'Chaîne rhénane structurante',
  },
  {
    id: 'hyd-iffezheim',
    name: 'Iffezheim',
    type: 'hydro_production',
    subtype: 'run_of_river',
    location: { lat: 48.806, lon: 8.142, region: 'Grand Est', country: 'FR' },
    capacity_mw: 148,
    reservoir_volume: null,
    operator: 'EDF',
    river: 'Rhin',
    selection_reason: 'Chaîne rhénane structurante',
  },
  {
    id: 'hyd-serre-poncon',
    name: 'Serre-Ponçon',
    type: 'hydro_production',
    subtype: 'dam',
    location: { lat: 44.533, lon: 6.316, region: "Provence-Alpes-Côte d'Azur", country: 'FR' },
    capacity_mw: 380,
    reservoir_volume: 1272,
    operator: 'EDF',
    river: 'Durance',
    selection_reason: 'Réservoir systémique de la Durance',
  },
  {
    id: 'hyd-saint-chamas',
    name: 'Saint-Chamas',
    type: 'hydro_production',
    subtype: 'run_of_river',
    location: { lat: 43.552, lon: 5.04, region: "Provence-Alpes-Côte d'Azur", country: 'FR' },
    capacity_mw: 240,
    reservoir_volume: null,
    operator: 'EDF',
    river: 'Durance',
    selection_reason: 'Nœud terminal de la chaîne Durance-Verdon',
  },
  {
    id: 'hyd-sainte-croix',
    name: 'Sainte-Croix',
    type: 'water_regulation',
    subtype: 'reservoir',
    location: { lat: 43.76, lon: 6.151, region: "Provence-Alpes-Côte d'Azur", country: 'FR' },
    capacity_mw: null,
    reservoir_volume: 767,
    operator: 'EDF',
    river: 'Verdon',
    selection_reason: 'Réservoir majeur du Verdon à impact systémique',
  },
  {
    id: 'hyd-castillon',
    name: 'Castillon',
    type: 'hydro_production',
    subtype: 'dam',
    location: { lat: 43.881, lon: 6.515, region: "Provence-Alpes-Côte d'Azur", country: 'FR' },
    capacity_mw: 85,
    reservoir_volume: 150,
    operator: 'EDF',
    river: 'Verdon',
    selection_reason: 'Barrage majeur amont Verdon',
  },
  {
    id: 'hyd-chaudanne',
    name: 'Chaudanne',
    type: 'hydro_production',
    subtype: 'dam',
    location: { lat: 43.802, lon: 6.492, region: "Provence-Alpes-Côte d'Azur", country: 'FR' },
    capacity_mw: 57,
    reservoir_volume: 27,
    operator: 'EDF',
    river: 'Verdon',
    selection_reason: 'Maillon critique de la cascade Verdon',
  },
  {
    id: 'hyd-la-rance',
    name: 'Usine marémotrice de la Rance',
    type: 'hydro_production',
    subtype: 'run_of_river',
    location: { lat: 48.621, lon: -1.973, region: 'Bretagne', country: 'FR' },
    capacity_mw: 240,
    reservoir_volume: null,
    operator: 'EDF',
    river: 'Rance',
    selection_reason: 'Actif hydraulique singulier de la façade Manche',
  },
  {
    id: 'hyd-guerledan',
    name: 'Guerlédan',
    type: 'water_regulation',
    subtype: 'reservoir',
    location: { lat: 48.198, lon: -3.041, region: 'Bretagne', country: 'FR' },
    capacity_mw: 15,
    reservoir_volume: 51,
    operator: 'EDF',
    river: 'Blavet',
    selection_reason: 'Réservoir structurant pour la Bretagne intérieure',
  },
  {
    id: 'hyd-calacuccia',
    name: 'Calacuccia',
    type: 'water_regulation',
    subtype: 'reservoir',
    location: { lat: 42.338, lon: 9.011, region: 'Corse', country: 'FR' },
    capacity_mw: 18,
    reservoir_volume: 25,
    operator: 'EDF SEI',
    river: 'Golo',
    selection_reason: 'Réservoir systémique corse',
  },
  {
    id: 'hyd-tolla',
    name: 'Tolla',
    type: 'water_regulation',
    subtype: 'reservoir',
    location: { lat: 41.977, lon: 8.934, region: 'Corse', country: 'FR' },
    capacity_mw: 17,
    reservoir_volume: 34,
    operator: 'EDF SEI',
    river: 'Prunelli',
    selection_reason: 'Réservoir systémique corse',
  },
  {
    id: 'hyd-ospedale',
    name: "L'Ospedale",
    type: 'water_regulation',
    subtype: 'reservoir',
    location: { lat: 41.679, lon: 9.247, region: 'Corse', country: 'FR' },
    capacity_mw: null,
    reservoir_volume: 13,
    operator: 'Collectivité de Corse',
    river: null,
    selection_reason: 'Réservoir critique pour le Sud corse',
  },
  {
    id: 'hyd-sampolo',
    name: 'Sampolo',
    type: 'hydro_production',
    subtype: 'dam',
    location: { lat: 41.914, lon: 9.132, region: 'Corse', country: 'FR' },
    capacity_mw: 43,
    reservoir_volume: 45,
    operator: 'EDF SEI',
    river: 'Travo',
    selection_reason: 'Hydro corse à fort impact insulaire',
  },
  {
    id: 'hyd-petit-saut',
    name: 'Petit-Saut',
    type: 'hydro_production',
    subtype: 'dam',
    location: { lat: 5.061, lon: -53.032, region: 'Guyane', country: 'FR' },
    capacity_mw: 116,
    reservoir_volume: 3650,
    operator: 'EDF SEI',
    river: 'Sinnamary',
    selection_reason: 'Actif critique DROM explicitement prioritaire',
  },
  {
    id: 'hyd-takamaka-ii',
    name: 'Takamaka II',
    type: 'hydro_production',
    subtype: 'dam',
    location: { lat: -21.07, lon: 55.613, region: 'La Réunion', country: 'FR' },
    capacity_mw: 26,
    reservoir_volume: null,
    operator: 'EDF SEI',
    river: 'Rivière des Marsouins',
    selection_reason: 'Hydro insulaire à forte valeur de résilience',
  },
  {
    id: 'hyd-riviere-de-lest',
    name: "Rivière de l'Est",
    type: 'hydro_production',
    subtype: 'run_of_river',
    location: { lat: -21.087, lon: 55.719, region: 'La Réunion', country: 'FR' },
    capacity_mw: 82,
    reservoir_volume: null,
    operator: 'EDF SEI',
    river: "Rivière de l'Est",
    selection_reason: 'Hydro insulaire à forte valeur de résilience',
  },
  {
    id: 'hyd-manzo',
    name: 'Manzo',
    type: 'water_regulation',
    subtype: 'reservoir',
    location: { lat: 14.668, lon: -60.991, region: 'Martinique', country: 'FR' },
    capacity_mw: null,
    reservoir_volume: 8,
    operator: 'CTM / Odyssi',
    river: 'Lézarde',
    selection_reason: 'Réservoir systémique insulaire',
  },
  {
    id: 'hyd-moreau',
    name: 'Moreau',
    type: 'water_regulation',
    subtype: 'reservoir',
    location: { lat: 16.172, lon: -61.619, region: 'Guadeloupe', country: 'FR' },
    capacity_mw: null,
    reservoir_volume: 10,
    operator: 'SMGEAG',
    river: 'Moreau',
    selection_reason: 'Réservoir systémique insulaire',
  },

  // ─── Sélection issue du référentiel open data hydro (>50 MW, bassin Adour-Garonne) ───
  {
    id: 'hyd-montezic',
    name: 'Montézic',
    type: 'step_storage',
    subtype: 'pumped_storage',
    location: { lat: 44.729047, lon: 2.643635, region: 'Occitanie', country: 'FR' },
    capacity_mw: 966.5,
    reservoir_volume: null,
    operator: 'EDF',
    river: 'Truyère',
    selection_reason: '>50 MW (référentiel hydro open data)',
  },
  {
    id: 'hyd-centrale-moulinette',
    name: 'Centrale Moulinette',
    type: 'hydro_production',
    subtype: 'run_of_river',
    location: { lat: 42.890681, lon: 1.781052, region: 'Occitanie', country: 'FR' },
    capacity_mw: 426,
    reservoir_volume: null,
    operator: 'Prolec',
    river: 'Ariège',
    selection_reason: '>50 MW (référentiel hydro open data)',
  },
  {
    id: 'hyd-brommat',
    name: 'Brommat',
    type: 'hydro_production',
    subtype: 'dam',
    location: { lat: 44.767893, lon: 2.683079, region: 'Occitanie', country: 'FR' },
    capacity_mw: 416.1,
    reservoir_volume: null,
    operator: 'EDF',
    river: 'Truyère',
    selection_reason: '>50 MW (référentiel hydro open data)',
  },
  {
    id: 'hyd-le-pouget',
    name: 'Le Pouget',
    type: 'hydro_production',
    subtype: 'dam',
    location: { lat: 44.058952, lon: 2.768559, region: 'Occitanie', country: 'FR' },
    capacity_mw: 409,
    reservoir_volume: null,
    operator: 'EDF',
    river: 'Tarn',
    selection_reason: '>50 MW (référentiel hydro open data)',
  },
  {
    id: 'hyd-aigle',
    name: "L'Aigle",
    type: 'hydro_production',
    subtype: 'dam',
    location: { lat: 45.243249, lon: 2.224798, region: 'Nouvelle-Aquitaine', country: 'FR' },
    capacity_mw: 360,
    reservoir_volume: 220,
    operator: 'EDF',
    river: 'Dordogne',
    selection_reason: '>50 MW (référentiel hydro open data)',
  },
  {
    id: 'hyd-chastang',
    name: 'Chastang',
    type: 'hydro_production',
    subtype: 'dam',
    location: { lat: 45.151531, lon: 2.0095, region: 'Nouvelle-Aquitaine', country: 'FR' },
    capacity_mw: 290,
    reservoir_volume: null,
    operator: 'EDF',
    river: 'Dordogne',
    selection_reason: '>50 MW (référentiel hydro open data)',
  },
  {
    id: 'hyd-bort',
    name: 'Bort-les-Orgues',
    type: 'hydro_production',
    subtype: 'dam',
    location: { lat: 45.412904, lon: 2.498423, region: 'Nouvelle-Aquitaine', country: 'FR' },
    capacity_mw: 232.8,
    reservoir_volume: 477,
    operator: 'EDF',
    river: 'Dordogne',
    selection_reason: '>50 MW (référentiel hydro open data)',
  },
  {
    id: 'hyd-pragneres',
    name: 'Pragnères',
    type: 'hydro_production',
    subtype: 'dam',
    location: { lat: 42.820835, lon: 0.010746, region: 'Occitanie', country: 'FR' },
    capacity_mw: 270,
    reservoir_volume: null,
    operator: 'EDF',
    river: 'Gave de Gavarnie',
    selection_reason: 'Fusion des deux groupes Pragnères pour limiter le bruit cartographique',
  },
  {
    id: 'hyd-sarrans',
    name: 'Sarrans',
    type: 'hydro_production',
    subtype: 'dam',
    location: { lat: 44.828686, lon: 2.740047, region: 'Occitanie', country: 'FR' },
    capacity_mw: 183,
    reservoir_volume: 296,
    operator: 'EDF',
    river: 'Truyère',
    selection_reason: '>50 MW (référentiel hydro open data)',
  },
  {
    id: 'hyd-mareges-saint-pierre',
    name: 'Marèges - Saint-Pierre',
    type: 'hydro_production',
    subtype: 'dam',
    location: { lat: 45.3902, lon: 2.3655, region: 'Nouvelle-Aquitaine', country: 'FR' },
    capacity_mw: 266.2,
    reservoir_volume: 47,
    operator: 'SHEM',
    river: 'Dordogne',
    selection_reason: 'Fusion de deux usines contiguës pour éviter la duplication',
  },
  {
    id: 'hyd-couesque',
    name: 'Couesque',
    type: 'hydro_production',
    subtype: 'dam',
    location: { lat: 44.695342, lon: 2.582693, region: 'Occitanie', country: 'FR' },
    capacity_mw: 124.5,
    reservoir_volume: null,
    operator: 'EDF',
    river: 'Truyère',
    selection_reason: '>50 MW (référentiel hydro open data)',
  },
  {
    id: 'hyd-st-etienne-cantales',
    name: 'Saint-Étienne-Cantalès',
    type: 'hydro_production',
    subtype: 'dam',
    location: { lat: 44.945627, lon: 2.219005, region: 'Auvergne-Rhône-Alpes', country: 'FR' },
    capacity_mw: 106.5,
    reservoir_volume: 133,
    operator: 'EDF',
    river: 'Cère',
    selection_reason: '>50 MW (référentiel hydro open data)',
  },
  {
    id: 'hyd-aston',
    name: 'Aston',
    type: 'hydro_production',
    subtype: 'dam',
    location: { lat: 42.776675, lon: 1.677133, region: 'Occitanie', country: 'FR' },
    capacity_mw: 105.9,
    reservoir_volume: null,
    operator: 'EDF',
    river: 'Aston',
    selection_reason: '>50 MW (référentiel hydro open data)',
  },
  {
    id: 'hyd-pont-de-camps',
    name: 'Pont de Camps',
    type: 'hydro_production',
    subtype: 'dam',
    location: { lat: 42.864489, lon: -0.392265, region: 'Nouvelle-Aquitaine', country: 'FR' },
    capacity_mw: 103.9,
    reservoir_volume: null,
    operator: 'SHEM',
    river: "Gave d'Ossau",
    selection_reason: '>50 MW (référentiel hydro open data)',
  },
  {
    id: 'hyd-laval-de-cere-2',
    name: 'Laval de Cère 2',
    type: 'hydro_production',
    subtype: 'dam',
    location: { lat: 44.953292, lon: 1.951928, region: 'Occitanie', country: 'FR' },
    capacity_mw: 96,
    reservoir_volume: null,
    operator: 'EDF',
    river: 'Cère',
    selection_reason: '>50 MW (référentiel hydro open data)',
  },
  {
    id: 'hyd-hospitalet-haute-chute',
    name: "L'Hospitalet Haute Chute",
    type: 'hydro_production',
    subtype: 'dam',
    location: { lat: 42.587987, lon: 1.796899, region: 'Occitanie', country: 'FR' },
    capacity_mw: 93.3,
    reservoir_volume: null,
    operator: 'EDF',
    river: 'Ariège',
    selection_reason: '>50 MW (référentiel hydro open data)',
  },
  {
    id: 'hyd-orlu',
    name: 'Orlu',
    type: 'hydro_production',
    subtype: 'dam',
    location: { lat: 42.689154, lon: 1.911355, region: 'Occitanie', country: 'FR' },
    capacity_mw: 88.6,
    reservoir_volume: null,
    operator: 'EDF',
    river: 'Oriège',
    selection_reason: '>50 MW (référentiel hydro open data)',
  },
  {
    id: 'hyd-montahut',
    name: 'Montahut',
    type: 'hydro_production',
    subtype: 'dam',
    location: { lat: 43.572166, lon: 2.934962, region: 'Occitanie', country: 'FR' },
    capacity_mw: 87,
    reservoir_volume: null,
    operator: 'EDF',
    river: 'Aude',
    selection_reason: '>50 MW (référentiel hydro open data)',
  },
  {
    id: 'hyd-miegebat',
    name: 'Miégebat',
    type: 'hydro_production',
    subtype: 'dam',
    location: { lat: 42.932214, lon: -0.446498, region: 'Nouvelle-Aquitaine', country: 'FR' },
    capacity_mw: 82.5,
    reservoir_volume: null,
    operator: 'SHEM',
    river: "Gave d'Ossau",
    selection_reason: '>50 MW (référentiel hydro open data)',
  },
  {
    id: 'hyd-grandval',
    name: 'Grandval',
    type: 'hydro_production',
    subtype: 'dam',
    location: { lat: 44.922155, lon: 3.074054, region: 'Auvergne-Rhône-Alpes', country: 'FR' },
    capacity_mw: 74.1,
    reservoir_volume: 270,
    operator: 'EDF',
    river: 'Truyère',
    selection_reason: '>50 MW (référentiel hydro open data)',
  },
  {
    id: 'hyd-portillon-haute-chute',
    name: 'Portillon Haute Chute',
    type: 'hydro_production',
    subtype: 'dam',
    location: { lat: 42.732388, lon: 0.552162, region: 'Occitanie', country: 'FR' },
    capacity_mw: 55,
    reservoir_volume: null,
    operator: 'EDF',
    river: 'Pique',
    selection_reason: '>50 MW (référentiel hydro open data)',
  },
  {
    id: 'hyd-auzat',
    name: 'Auzat',
    type: 'hydro_production',
    subtype: 'run_of_river',
    location: { lat: 42.761271, lon: 1.478005, region: 'Occitanie', country: 'FR' },
    capacity_mw: 52.2,
    reservoir_volume: null,
    operator: 'EDF',
    river: 'Vicdessos',
    selection_reason: '>50 MW (référentiel hydro open data)',
  },
  {
    id: 'hyd-lardit',
    name: 'Lardit',
    type: 'hydro_production',
    subtype: 'dam',
    location: { lat: 44.662349, lon: 2.583168, region: 'Occitanie', country: 'FR' },
    capacity_mw: 51.2,
    reservoir_volume: null,
    operator: 'EDF',
    river: 'Selves',
    selection_reason: '>50 MW (référentiel hydro open data)',
  },
];

export const HYDRAULIC_BACKBONE_SEEDS: HydraulicBackboneSeed[] = [
  ...HYDRAULIC_MANUAL_BACKBONE_SEEDS,
  ...HYDRAULIC_OFFICIAL_BACKBONE_SEEDS,
];
