/**
 * MMSI Maritime Identification Digit (MID) → Country + flag emoji
 * Source: ITU Table of Maritime Identification Digits
 * First 3 digits of a 9-digit MMSI encode the flag state.
 */

interface MidEntry { name: string; iso2: string; }

const MID_TABLE: Record<number, MidEntry> = {
  // Europe
  201: { name: 'Albanie', iso2: 'AL' },
  203: { name: 'Autriche', iso2: 'AT' },
  204: { name: 'Açores', iso2: 'PT' },
  205: { name: 'Belgique', iso2: 'BE' },
  206: { name: 'Biélorussie', iso2: 'BY' },
  207: { name: 'Bulgarie', iso2: 'BG' },
  208: { name: 'Vatican', iso2: 'VA' },
  209: { name: 'Chypre', iso2: 'CY' },
  210: { name: 'Chypre', iso2: 'CY' },
  211: { name: 'Allemagne', iso2: 'DE' },
  212: { name: 'Chypre', iso2: 'CY' },
  213: { name: 'Géorgie', iso2: 'GE' },
  214: { name: 'Moldavie', iso2: 'MD' },
  215: { name: 'Malte', iso2: 'MT' },
  216: { name: 'Arménie', iso2: 'AM' },
  218: { name: 'Allemagne', iso2: 'DE' },
  219: { name: 'Danemark', iso2: 'DK' },
  220: { name: 'Danemark', iso2: 'DK' },
  224: { name: 'Espagne', iso2: 'ES' },
  225: { name: 'Espagne', iso2: 'ES' },
  226: { name: 'France', iso2: 'FR' },
  227: { name: 'France', iso2: 'FR' },
  228: { name: 'France', iso2: 'FR' },
  229: { name: 'Malte', iso2: 'MT' },
  230: { name: 'Finlande', iso2: 'FI' },
  231: { name: 'Îles Féroé', iso2: 'FO' },
  232: { name: 'Royaume-Uni', iso2: 'GB' },
  233: { name: 'Royaume-Uni', iso2: 'GB' },
  234: { name: 'Royaume-Uni', iso2: 'GB' },
  235: { name: 'Royaume-Uni', iso2: 'GB' },
  236: { name: 'Gibraltar', iso2: 'GI' },
  237: { name: 'Grèce', iso2: 'GR' },
  238: { name: 'Croatie', iso2: 'HR' },
  239: { name: 'Grèce', iso2: 'GR' },
  240: { name: 'Grèce', iso2: 'GR' },
  241: { name: 'Grèce', iso2: 'GR' },
  242: { name: 'Maroc', iso2: 'MA' },
  243: { name: 'Hongrie', iso2: 'HU' },
  244: { name: 'Pays-Bas', iso2: 'NL' },
  245: { name: 'Pays-Bas', iso2: 'NL' },
  246: { name: 'Pays-Bas', iso2: 'NL' },
  247: { name: 'Italie', iso2: 'IT' },
  248: { name: 'Malte', iso2: 'MT' },
  249: { name: 'Malte', iso2: 'MT' },
  250: { name: 'Irlande', iso2: 'IE' },
  251: { name: 'Islande', iso2: 'IS' },
  252: { name: 'Liechtenstein', iso2: 'LI' },
  253: { name: 'Luxembourg', iso2: 'LU' },
  254: { name: 'Monaco', iso2: 'MC' },
  255: { name: 'Madère', iso2: 'PT' },
  256: { name: 'Malte', iso2: 'MT' },
  257: { name: 'Norvège', iso2: 'NO' },
  258: { name: 'Norvège', iso2: 'NO' },
  259: { name: 'Norvège', iso2: 'NO' },
  261: { name: 'Pologne', iso2: 'PL' },
  263: { name: 'Portugal', iso2: 'PT' },
  264: { name: 'Roumanie', iso2: 'RO' },
  265: { name: 'Suède', iso2: 'SE' },
  266: { name: 'Suède', iso2: 'SE' },
  267: { name: 'Slovaquie', iso2: 'SK' },
  268: { name: 'Saint-Marin', iso2: 'SM' },
  269: { name: 'Suisse', iso2: 'CH' },
  270: { name: 'Tchéquie', iso2: 'CZ' },
  271: { name: 'Turquie', iso2: 'TR' },
  272: { name: 'Ukraine', iso2: 'UA' },
  273: { name: 'Russie', iso2: 'RU' },
  274: { name: 'Macédoine', iso2: 'MK' },
  275: { name: 'Lettonie', iso2: 'LV' },
  276: { name: 'Estonie', iso2: 'EE' },
  277: { name: 'Lituanie', iso2: 'LT' },
  278: { name: 'Slovénie', iso2: 'SI' },
  // Amériques
  301: { name: 'Anguilla', iso2: 'AI' },
  303: { name: 'Alaska (USA)', iso2: 'US' },
  304: { name: 'Antigua-et-Barbuda', iso2: 'AG' },
  305: { name: 'Antigua-et-Barbuda', iso2: 'AG' },
  306: { name: 'Antilles néerlandaises', iso2: 'NL' },
  307: { name: 'Aruba', iso2: 'AW' },
  308: { name: 'Bahamas', iso2: 'BS' },
  309: { name: 'Bahamas', iso2: 'BS' },
  310: { name: 'Bermudes', iso2: 'BM' },
  311: { name: 'Bahamas', iso2: 'BS' },
  312: { name: 'Belize', iso2: 'BZ' },
  314: { name: 'Barbade', iso2: 'BB' },
  316: { name: 'Canada', iso2: 'CA' },
  319: { name: 'Îles Caïmans', iso2: 'KY' },
  321: { name: 'Costa Rica', iso2: 'CR' },
  323: { name: 'Cuba', iso2: 'CU' },
  325: { name: 'Dominique', iso2: 'DM' },
  327: { name: 'République dominicaine', iso2: 'DO' },
  329: { name: 'Guadeloupe', iso2: 'FR' },
  330: { name: 'Grenade', iso2: 'GD' },
  331: { name: 'Groenland', iso2: 'GL' },
  332: { name: 'Guatemala', iso2: 'GT' },
  334: { name: 'Honduras', iso2: 'HN' },
  336: { name: 'Haïti', iso2: 'HT' },
  338: { name: 'États-Unis', iso2: 'US' },
  339: { name: 'Jamaïque', iso2: 'JM' },
  341: { name: 'Saint-Kitts', iso2: 'KN' },
  343: { name: 'Sainte-Lucie', iso2: 'LC' },
  345: { name: 'Mexique', iso2: 'MX' },
  347: { name: 'Martinique', iso2: 'FR' },
  348: { name: 'Montserrat', iso2: 'MS' },
  350: { name: 'Nicaragua', iso2: 'NI' },
  351: { name: 'Panama', iso2: 'PA' },
  352: { name: 'Panama', iso2: 'PA' },
  353: { name: 'Panama', iso2: 'PA' },
  354: { name: 'Panama', iso2: 'PA' },
  355: { name: 'Panama', iso2: 'PA' },
  356: { name: 'Panama', iso2: 'PA' },
  357: { name: 'Panama', iso2: 'PA' },
  358: { name: 'Porto Rico', iso2: 'PR' },
  359: { name: 'Salvador', iso2: 'SV' },
  361: { name: 'Saint-Pierre-et-Miquelon', iso2: 'FR' },
  362: { name: 'Trinité-et-Tobago', iso2: 'TT' },
  364: { name: 'Turks-et-Caïcos', iso2: 'TC' },
  366: { name: 'États-Unis', iso2: 'US' },
  367: { name: 'États-Unis', iso2: 'US' },
  368: { name: 'États-Unis', iso2: 'US' },
  369: { name: 'États-Unis', iso2: 'US' },
  370: { name: 'Panama', iso2: 'PA' },
  371: { name: 'Panama', iso2: 'PA' },
  372: { name: 'Panama', iso2: 'PA' },
  373: { name: 'Panama', iso2: 'PA' },
  374: { name: 'Panama', iso2: 'PA' },
  375: { name: 'Saint-Vincent', iso2: 'VC' },
  376: { name: 'Saint-Vincent', iso2: 'VC' },
  377: { name: 'Saint-Vincent', iso2: 'VC' },
  378: { name: 'Îles Vierges brit.', iso2: 'VG' },
  379: { name: 'Îles Vierges USA', iso2: 'VI' },
  // Asie / Proche-Orient
  401: { name: 'Afghanistan', iso2: 'AF' },
  403: { name: 'Arabie saoudite', iso2: 'SA' },
  405: { name: 'Bangladesh', iso2: 'BD' },
  408: { name: 'Bahreïn', iso2: 'BH' },
  412: { name: 'Chine', iso2: 'CN' },
  413: { name: 'Chine', iso2: 'CN' },
  414: { name: 'Chine', iso2: 'CN' },
  416: { name: 'Taïwan', iso2: 'TW' },
  417: { name: 'Sri Lanka', iso2: 'LK' },
  419: { name: 'Inde', iso2: 'IN' },
  422: { name: 'Iran', iso2: 'IR' },
  423: { name: 'Azerbaïdjan', iso2: 'AZ' },
  425: { name: 'Irak', iso2: 'IQ' },
  428: { name: 'Israël', iso2: 'IL' },
  431: { name: 'Japon', iso2: 'JP' },
  432: { name: 'Japon', iso2: 'JP' },
  434: { name: 'Turkménistan', iso2: 'TM' },
  436: { name: 'Kazakhstan', iso2: 'KZ' },
  438: { name: 'Jordanie', iso2: 'JO' },
  440: { name: 'Corée du Sud', iso2: 'KR' },
  441: { name: 'Corée du Sud', iso2: 'KR' },
  443: { name: 'Palestine', iso2: 'PS' },
  445: { name: 'Corée du Nord', iso2: 'KP' },
  447: { name: 'Koweït', iso2: 'KW' },
  450: { name: 'Liban', iso2: 'LB' },
  453: { name: 'Macao', iso2: 'MO' },
  455: { name: 'Maldives', iso2: 'MV' },
  461: { name: 'Oman', iso2: 'OM' },
  463: { name: 'Pakistan', iso2: 'PK' },
  466: { name: 'Qatar', iso2: 'QA' },
  468: { name: 'Syrie', iso2: 'SY' },
  470: { name: 'Émirats arabes unis', iso2: 'AE' },
  472: { name: 'Tadjikistan', iso2: 'TJ' },
  473: { name: 'Yémen', iso2: 'YE' },
  477: { name: 'Hong Kong', iso2: 'HK' },
  478: { name: 'Bosnie', iso2: 'BA' },
  // Pacifique / Océanie
  503: { name: 'Australie', iso2: 'AU' },
  506: { name: 'Myanmar', iso2: 'MM' },
  508: { name: 'Brunei', iso2: 'BN' },
  510: { name: 'Micronésie', iso2: 'FM' },
  512: { name: 'Nouvelle-Zélande', iso2: 'NZ' },
  514: { name: 'Cambodge', iso2: 'KH' },
  515: { name: 'Cambodge', iso2: 'KH' },
  520: { name: 'Fidji', iso2: 'FJ' },
  525: { name: 'Indonésie', iso2: 'ID' },
  533: { name: 'Malaisie', iso2: 'MY' },
  536: { name: 'Îles Mariannes', iso2: 'MP' },
  538: { name: 'Îles Marshall', iso2: 'MH' },
  540: { name: 'Nouvelle-Calédonie', iso2: 'FR' },
  542: { name: 'Niue', iso2: 'NU' },
  546: { name: 'Polynésie française', iso2: 'FR' },
  548: { name: 'Philippines', iso2: 'PH' },
  553: { name: 'Papouasie', iso2: 'PG' },
  557: { name: 'Îles Salomon', iso2: 'SB' },
  559: { name: 'Samoa américaines', iso2: 'AS' },
  561: { name: 'Samoa', iso2: 'WS' },
  563: { name: 'Singapour', iso2: 'SG' },
  564: { name: 'Singapour', iso2: 'SG' },
  565: { name: 'Singapour', iso2: 'SG' },
  566: { name: 'Singapour', iso2: 'SG' },
  567: { name: 'Thaïlande', iso2: 'TH' },
  574: { name: 'Viêt Nam', iso2: 'VN' },
  576: { name: 'Vanuatu', iso2: 'VU' },
  // Afrique
  601: { name: 'Afrique du Sud', iso2: 'ZA' },
  603: { name: 'Angola', iso2: 'AO' },
  605: { name: 'Algérie', iso2: 'DZ' },
  607: { name: 'Bénin', iso2: 'BJ' },
  611: { name: 'Cameroun', iso2: 'CM' },
  612: { name: 'Cap-Vert', iso2: 'CV' },
  615: { name: 'Congo', iso2: 'CG' },
  616: { name: 'Comores', iso2: 'KM' },
  617: { name: 'RD Congo', iso2: 'CD' },
  620: { name: 'Égypte', iso2: 'EG' },
  621: { name: 'Guinée équatoriale', iso2: 'GQ' },
  624: { name: 'Érythrée', iso2: 'ER' },
  625: { name: 'Gabon', iso2: 'GA' },
  626: { name: 'Gambie', iso2: 'GM' },
  627: { name: 'Ghana', iso2: 'GH' },
  629: { name: 'Guinée', iso2: 'GN' },
  630: { name: 'Guinée-Bissau', iso2: 'GW' },
  631: { name: 'Kenya', iso2: 'KE' },
  633: { name: 'Liberia', iso2: 'LR' },
  634: { name: 'Liberia', iso2: 'LR' },
  635: { name: 'Liberia', iso2: 'LR' },
  636: { name: 'Liberia', iso2: 'LR' },
  637: { name: 'Libye', iso2: 'LY' },
  642: { name: 'Madagascar', iso2: 'MG' },
  644: { name: 'Malawi', iso2: 'MW' },
  645: { name: 'Mali', iso2: 'ML' },
  647: { name: 'Mauritanie', iso2: 'MR' },
  649: { name: 'Maurice', iso2: 'MU' },
  650: { name: 'Mozambique', iso2: 'MZ' },
  654: { name: 'Namibie', iso2: 'NA' },
  656: { name: 'Nigeria', iso2: 'NG' },
  660: { name: 'Sénégal', iso2: 'SN' },
  661: { name: 'Sierra Leone', iso2: 'SL' },
  662: { name: 'Somalie', iso2: 'SO' },
  663: { name: 'Afrique du Sud', iso2: 'ZA' },
  664: { name: 'Soudan', iso2: 'SD' },
  667: { name: 'Tanzanie', iso2: 'TZ' },
  668: { name: 'Togo', iso2: 'TG' },
  669: { name: 'Tunisie', iso2: 'TN' },
  670: { name: 'Ouganda', iso2: 'UG' },
  // Amérique du Sud
  701: { name: 'Argentine', iso2: 'AR' },
  710: { name: 'Brésil', iso2: 'BR' },
  720: { name: 'Bolivie', iso2: 'BO' },
  725: { name: 'Chili', iso2: 'CL' },
  730: { name: 'Colombie', iso2: 'CO' },
  735: { name: 'Équateur', iso2: 'EC' },
  740: { name: 'Îles Falkland', iso2: 'FK' },
  745: { name: 'Guyane française', iso2: 'FR' },
  750: { name: 'Guyana', iso2: 'GY' },
  755: { name: 'Paraguay', iso2: 'PY' },
  760: { name: 'Pérou', iso2: 'PE' },
  765: { name: 'Suriname', iso2: 'SR' },
  770: { name: 'Uruguay', iso2: 'UY' },
  775: { name: 'Venezuela', iso2: 'VE' },
};

/**
 * Convert ISO2 country code to flag emoji (regional indicator letters)
 */
export function iso2ToFlag(iso2: string): string {
  if (!iso2 || iso2.length !== 2) return '🏳️';
  const codePoints = [...iso2.toUpperCase()].map(c => 0x1F1E0 + c.charCodeAt(0) - 65);
  return String.fromCodePoint(...codePoints);
}

/**
 * Get country name and flag emoji from MMSI
 * @param mmsi - MMSI string (9 digits)
 */
export function getMmsiCountry(mmsi: string): { name: string; flag: string; iso2: string } | null {
  if (!mmsi || mmsi.length < 3) return null;
  const mid = parseInt(mmsi.slice(0, 3), 10);
  const entry = MID_TABLE[mid];
  if (!entry) return null;
  return {
    name: entry.name,
    flag: iso2ToFlag(entry.iso2),
    iso2: entry.iso2,
  };
}
