// GÉNÉRÉ par scripts/generate-api-routes.mjs — ne pas éditer à la main.
// Régénérer après tout ajout, renommage ou suppression dans api/_handlers/ : npm run generate:api-routes

/** @type {Record<string, () => Promise<Record<string, unknown>>>} */
export const ROUTES = {
  '/api/arcep': () => import('./_handlers/arcep.js'),
  '/api/citizen-outages': () => import('./_handlers/citizen-outages.js'),
  '/api/copernicus': () => import('./_handlers/copernicus.js'),
  '/api/energy/biogas-sites': () => import('./_handlers/energy/biogas-sites.js'),
  '/api/energy/biogas': () => import('./_handlers/energy/biogas.js'),
  '/api/energy/drom-live': () => import('./_handlers/energy/drom-live.js'),
  '/api/energy/drom': () => import('./_handlers/energy/drom.js'),
  '/api/energy/ecowatt-signal': () => import('./_handlers/energy/ecowatt-signal.js'),
  '/api/energy/ecowatt': () => import('./_handlers/energy/ecowatt.js'),
  '/api/energy/eolien': () => import('./_handlers/energy/eolien.js'),
  '/api/energy/gas-pir': () => import('./_handlers/energy/gas-pir.js'),
  '/api/events/changes': () => import('./_handlers/events/changes.js'),
  '/api/events/detail': () => import('./_handlers/events/detail.js'),
  '/api/events': () => import('./_handlers/events.js'),
  '/api/exposure': () => import('./_handlers/exposure.js'),
  '/api/finance/commodities': () => import('./_handlers/finance/commodities.js'),
  '/api/finance/market': () => import('./_handlers/finance/market.js'),
  '/api/fire-observations/mtg-frp': () => import('./_handlers/fire-observations/mtg-frp.js'),
  '/api/fire-observations/radar-2d': () => import('./_handlers/fire-observations/radar-2d.js'),
  '/api/fire-observations/radar-column': () => import('./_handlers/fire-observations/radar-column.js'),
  '/api/fires': () => import('./_handlers/fires.js'),
  '/api/fuel-price-series': () => import('./_handlers/fuel-price-series.js'),
  '/api/fuel-prices-proxy': () => import('./_handlers/fuel-prices-proxy.js'),
  '/api/geo/communes': () => import('./_handlers/geo/communes.js'),
  '/api/gie/agsi': () => import('./_handlers/gie/agsi.js'),
  '/api/gie/alsi': () => import('./_handlers/gie/alsi.js'),
  '/api/health/alert-levels': () => import('./_handlers/health/alert-levels.js'),
  '/api/health/dgs-messages': () => import('./_handlers/health/dgs-messages.js'),
  '/api/health/drug-shortages': () => import('./_handlers/health/drug-shortages.js'),
  '/api/health/international': () => import('./_handlers/health/international.js'),
  '/api/health/recalls': () => import('./_handlers/health/recalls.js'),
  '/api/health/sentinelles-national': () => import('./_handlers/health/sentinelles-national.js'),
  '/api/health/syndromic': () => import('./_handlers/health/syndromic.js'),
  '/api/health/wastewater': () => import('./_handlers/health/wastewater.js'),
  '/api/health-check': () => import('./_handlers/health-check.js'),
  '/api/infra-network': () => import('./_handlers/infra-network.js'),
  '/api/intelligence/v1/france-intel-brief': () => import('./_handlers/intelligence/v1/france-intel-brief.js'),
  '/api/intelligence/v1/summarize': () => import('./_handlers/intelligence/v1/summarize.js'),
  '/api/intelligence/v1/synthesis': () => import('./_handlers/intelligence/v1/synthesis.js'),
  '/api/internet-outages': () => import('./_handlers/internet-outages.js'),
  '/api/json-proxy': () => import('./_handlers/json-proxy.js'),
  '/api/ministers/agenda': () => import('./_handlers/ministers/agenda.js'),
  '/api/ministers/composition': () => import('./_handlers/ministers/composition.js'),
  '/api/ministers/opendata': () => import('./_handlers/ministers/opendata.js'),
  '/api/ministers/prime-minister': () => import('./_handlers/ministers/prime-minister.js'),
  '/api/ministers/profile-meta': () => import('./_handlers/ministers/profile-meta.js'),
  '/api/ministers/wikidata-search': () => import('./_handlers/ministers/wikidata-search.js'),
  '/api/ministers/wikidata': () => import('./_handlers/ministers/wikidata.js'),
  '/api/news/history': () => import('./_handlers/news/history.js'),
  '/api/news': () => import('./_handlers/news.js'),
  '/api/nuclear/rte-unavailability': () => import('./_handlers/nuclear/rte-unavailability.js'),
  '/api/oil-proxy': () => import('./_handlers/oil-proxy.js'),
  '/api/opendata-proxy': () => import('./_handlers/opendata-proxy.js'),
  '/api/rss-proxy': () => import('./_handlers/rss-proxy.js'),
  '/api/rss': () => import('./_handlers/rss.js'),
  '/api/rte-iip': () => import('./_handlers/rte-iip.js'),
  '/api/situation-history': () => import('./_handlers/situation-history.js'),
  '/api/threats': () => import('./_handlers/threats.js'),
  '/api/traffic/air-overview': () => import('./_handlers/traffic/air-overview.js'),
  '/api/traffic/air': () => import('./_handlers/traffic/air.js'),
  '/api/traffic/flow': () => import('./_handlers/traffic/flow.js'),
  '/api/traffic/military': () => import('./_handlers/traffic/military.js'),
  '/api/traffic/road-national': () => import('./_handlers/traffic/road-national.js'),
  '/api/traffic/road-urban': () => import('./_handlers/traffic/road-urban.js'),
  '/api/traffic/tile': () => import('./_handlers/traffic/tile.js'),
  '/api/transport/rail-overview': () => import('./_handlers/transport/rail-overview.js'),
  '/api/transport/rail-situations': () => import('./_handlers/transport/rail-situations.js'),
  '/api/weather/vigilance': () => import('./_handlers/weather/vigilance.js'),
};

/** @type {Record<string, string>} */
export const ALIASES = {
  '/api/outages/citizen': '/api/citizen-outages',
};
