// GÉNÉRÉ par scripts/generate-api-routes.mjs — ne pas éditer à la main.
// Régénérer après tout ajout, renommage ou suppression dans api/_handlers/ : npm run generate:api-routes

/** @type {Record<string, () => Promise<Record<string, unknown>>>} */
export const ROUTES = {
  '/api/arcep': () => import('./_handlers/arcep.js'),
  '/api/citizen-outages': () => import('./_handlers/citizen-outages.js'),
  '/api/copernicus': () => import('./_handlers/copernicus.js'),
  '/api/energy/biogas-sites': () => import('./_handlers/energy/biogas-sites.js'),
  '/api/energy/biogas': () => import('./_handlers/energy/biogas.js'),
  '/api/energy/drom': () => import('./_handlers/energy/drom.js'),
  '/api/energy/ecowatt': () => import('./_handlers/energy/ecowatt.js'),
  '/api/energy/eolien': () => import('./_handlers/energy/eolien.js'),
  '/api/energy/gas-pir': () => import('./_handlers/energy/gas-pir.js'),
  '/api/events/changes': () => import('./_handlers/events/changes.js'),
  '/api/events/detail': () => import('./_handlers/events/detail.js'),
  '/api/events': () => import('./_handlers/events.js'),
  '/api/exposure': () => import('./_handlers/exposure.js'),
  '/api/finance/commodities': () => import('./_handlers/finance/commodities.js'),
  '/api/finance/market': () => import('./_handlers/finance/market.js'),
  '/api/fire-observations/mtg-frp': () => import('./_handlers/fire-observations/mtg-frp.js'),
  '/api/fire-observations/radar-2d': () => import('./_handlers/fire-observations/radar-2d.js'),
  '/api/fire-observations/radar-column': () => import('./_handlers/fire-observations/radar-column.js'),
  '/api/fires': () => import('./_handlers/fires.js'),
  '/api/fuel-price-series': () => import('./_handlers/fuel-price-series.js'),
  '/api/fuel-prices-proxy': () => import('./_handlers/fuel-prices-proxy.js'),
  '/api/geo/communes': () => import('./_handlers/geo/communes.js'),
  '/api/gie/agsi': () => import('./_handlers/gie/agsi.js'),
  '/api/gie/alsi': () => import('./_handlers/gie/alsi.js'),
  '/api/health/apl': () => import('./_handlers/health/apl.js'),
  '/api/health/departmental': () => import('./_handlers/health/departmental.js'),
  '/api/health/drug-shortages': () => import('./_handlers/health/drug-shortages.js'),
  '/api/health/epidemic-alerts': () => import('./_handlers/health/epidemic-alerts.js'),
  '/api/health/epidemiology-monitor': () => import('./_handlers/health/epidemiology-monitor.js'),
  '/api/health/epidemiology': () => import('./_handlers/health/epidemiology.js'),
  '/api/health/hantavirus': () => import('./_handlers/health/hantavirus.js'),
  '/api/health/oscour-sos': () => import('./_handlers/health/oscour-sos.js'),
  '/api/health/sentinelles-ingestion': () => import('./_handlers/health/sentinelles-ingestion.js'),
  '/api/health/sentinelles': () => import('./_handlers/health/sentinelles.js'),
  '/api/health-check': () => import('./_handlers/health-check.js'),
  '/api/infra-network': () => import('./_handlers/infra-network.js'),
  '/api/intelligence/v1/france-intel-brief': () => import('./_handlers/intelligence/v1/france-intel-brief.js'),
  '/api/intelligence/v1/summarize': () => import('./_handlers/intelligence/v1/summarize.js'),
  '/api/intelligence/v1/synthesis': () => import('./_handlers/intelligence/v1/synthesis.js'),
  '/api/internet-outages': () => import('./_handlers/internet-outages.js'),
  '/api/json-proxy': () => import('./_handlers/json-proxy.js'),
  '/api/ministers/agenda': () => import('./_handlers/ministers/agenda.js'),
  '/api/ministers/composition': () => import('./_handlers/ministers/composition.js'),
  '/api/ministers/opendata': () => import('./_handlers/ministers/opendata.js'),
  '/api/ministers/prime-minister': () => import('./_handlers/ministers/prime-minister.js'),
  '/api/ministers/profile-meta': () => import('./_handlers/ministers/profile-meta.js'),
  '/api/ministers/wikidata-search': () => import('./_handlers/ministers/wikidata-search.js'),
  '/api/ministers/wikidata': () => import('./_handlers/ministers/wikidata.js'),
  '/api/news/history': () => import('./_handlers/news/history.js'),
  '/api/news': () => import('./_handlers/news.js'),
  '/api/nuclear/rte-unavailability': () => import('./_handlers/nuclear/rte-unavailability.js'),
  '/api/oil-proxy': () => import('./_handlers/oil-proxy.js'),
  '/api/opendata-proxy': () => import('./_handlers/opendata-proxy.js'),
  '/api/rss-proxy': () => import('./_handlers/rss-proxy.js'),
  '/api/rss': () => import('./_handlers/rss.js'),
  '/api/rte-iip': () => import('./_handlers/rte-iip.js'),
  '/api/situation-history': () => import('./_handlers/situation-history.js'),
  '/api/threats': () => import('./_handlers/threats.js'),
  '/api/traffic/air': () => import('./_handlers/traffic/air.js'),
  '/api/traffic/flow': () => import('./_handlers/traffic/flow.js'),
  '/api/traffic/military': () => import('./_handlers/traffic/military.js'),
  '/api/traffic/road': () => import('./_handlers/traffic/road.js'),
  '/api/traffic/tile': () => import('./_handlers/traffic/tile.js'),
  '/api/transport/disruptions': () => import('./_handlers/transport/disruptions.js'),
  '/api/transport/osm-railways': () => import('./_handlers/transport/osm-railways.js'),
  '/api/weather/vigilance': () => import('./_handlers/weather/vigilance.js'),
};

/** @type {Record<string, string>} */
export const ALIASES = {
  '/api/outages/citizen': '/api/citizen-outages',
};
